// Generated by CIRCT firtool-1.62.0
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

module TrapHandleModule(
  input         io_in_trapInfo_valid,
  input  [63:0] io_in_trapInfo_bits_trapVec,
  input  [63:0] io_in_trapInfo_bits_intrVec,
  input         io_in_trapInfo_bits_isInterrupt,
  input         io_in_trapInfo_bits_singleStep,
  input         io_in_trapInfo_bits_triggerFire,
  input  [1:0]  io_in_privState_PRVM,
  input         io_in_privState_V,
  input         io_in_mideleg_SSI,
  input         io_in_mideleg_STI,
  input         io_in_mideleg_SEI,
  input         io_in_mideleg_LCOFI,
  input         io_in_medeleg_EX_IAM,
  input         io_in_medeleg_EX_IAF,
  input         io_in_medeleg_EX_II,
  input         io_in_medeleg_EX_LAM,
  input         io_in_medeleg_EX_LAF,
  input         io_in_medeleg_EX_SAM,
  input         io_in_medeleg_EX_SAF,
  input         io_in_medeleg_EX_UCALL,
  input         io_in_medeleg_EX_HSCALL,
  input         io_in_medeleg_EX_VSCALL,
  input         io_in_medeleg_EX_IPF,
  input         io_in_medeleg_EX_LPF,
  input         io_in_medeleg_EX_SPF,
  input         io_in_medeleg_EX_IGPF,
  input         io_in_medeleg_EX_LGPF,
  input         io_in_medeleg_EX_VI,
  input         io_in_medeleg_EX_SGPF,
  input         io_in_hideleg_VSSI,
  input         io_in_hideleg_VSTI,
  input         io_in_hideleg_VSEI,
  input         io_in_hideleg_LCOFI,
  input         io_in_hedeleg_EX_IAM,
  input         io_in_hedeleg_EX_IAF,
  input         io_in_hedeleg_EX_II,
  input         io_in_hedeleg_EX_BP,
  input         io_in_hedeleg_EX_LAM,
  input         io_in_hedeleg_EX_LAF,
  input         io_in_hedeleg_EX_SAM,
  input         io_in_hedeleg_EX_SAF,
  input         io_in_hedeleg_EX_UCALL,
  input         io_in_hedeleg_EX_IPF,
  input         io_in_hedeleg_EX_LPF,
  input         io_in_hedeleg_EX_SPF,
  input         io_in_mvien_SSIE,
  input         io_in_mvien_SEIE,
  input         io_in_mvien_LCOFIE,
  input         io_in_mvien_LC14IE,
  input         io_in_mvien_LC15IE,
  input         io_in_mvien_LC16IE,
  input         io_in_mvien_LC17IE,
  input         io_in_mvien_LC18IE,
  input         io_in_mvien_LC19IE,
  input         io_in_mvien_LC20IE,
  input         io_in_mvien_LC21IE,
  input         io_in_mvien_LC22IE,
  input         io_in_mvien_LC23IE,
  input         io_in_mvien_LC24IE,
  input         io_in_mvien_LC25IE,
  input         io_in_mvien_LC26IE,
  input         io_in_mvien_LC27IE,
  input         io_in_mvien_LC28IE,
  input         io_in_mvien_LC29IE,
  input         io_in_mvien_LC30IE,
  input         io_in_mvien_LC31IE,
  input         io_in_mvien_LC32IE,
  input         io_in_mvien_LC33IE,
  input         io_in_mvien_LC34IE,
  input         io_in_mvien_LPRASEIE,
  input         io_in_mvien_LC36IE,
  input         io_in_mvien_LC37IE,
  input         io_in_mvien_LC38IE,
  input         io_in_mvien_LC39IE,
  input         io_in_mvien_LC40IE,
  input         io_in_mvien_LC41IE,
  input         io_in_mvien_LC42IE,
  input         io_in_mvien_HPRASEIE,
  input         io_in_mvien_LC44IE,
  input         io_in_mvien_LC45IE,
  input         io_in_mvien_LC46IE,
  input         io_in_mvien_LC47IE,
  input         io_in_mvien_LC48IE,
  input         io_in_mvien_LC49IE,
  input         io_in_mvien_LC50IE,
  input         io_in_mvien_LC51IE,
  input         io_in_mvien_LC52IE,
  input         io_in_mvien_LC53IE,
  input         io_in_mvien_LC54IE,
  input         io_in_mvien_LC55IE,
  input         io_in_mvien_LC56IE,
  input         io_in_mvien_LC57IE,
  input         io_in_mvien_LC58IE,
  input         io_in_mvien_LC59IE,
  input         io_in_mvien_LC60IE,
  input         io_in_mvien_LC61IE,
  input         io_in_mvien_LC62IE,
  input         io_in_mvien_LC63IE,
  input         io_in_hvien_LCOFIE,
  input         io_in_hvien_LC14IE,
  input         io_in_hvien_LC15IE,
  input         io_in_hvien_LC16IE,
  input         io_in_hvien_LC17IE,
  input         io_in_hvien_LC18IE,
  input         io_in_hvien_LC19IE,
  input         io_in_hvien_LC20IE,
  input         io_in_hvien_LC21IE,
  input         io_in_hvien_LC22IE,
  input         io_in_hvien_LC23IE,
  input         io_in_hvien_LC24IE,
  input         io_in_hvien_LC25IE,
  input         io_in_hvien_LC26IE,
  input         io_in_hvien_LC27IE,
  input         io_in_hvien_LC28IE,
  input         io_in_hvien_LC29IE,
  input         io_in_hvien_LC30IE,
  input         io_in_hvien_LC31IE,
  input         io_in_hvien_LC32IE,
  input         io_in_hvien_LC33IE,
  input         io_in_hvien_LC34IE,
  input         io_in_hvien_LPRASEIE,
  input         io_in_hvien_LC36IE,
  input         io_in_hvien_LC37IE,
  input         io_in_hvien_LC38IE,
  input         io_in_hvien_LC39IE,
  input         io_in_hvien_LC40IE,
  input         io_in_hvien_LC41IE,
  input         io_in_hvien_LC42IE,
  input         io_in_hvien_HPRASEIE,
  input         io_in_hvien_LC44IE,
  input         io_in_hvien_LC45IE,
  input         io_in_hvien_LC46IE,
  input         io_in_hvien_LC47IE,
  input         io_in_hvien_LC48IE,
  input         io_in_hvien_LC49IE,
  input         io_in_hvien_LC50IE,
  input         io_in_hvien_LC51IE,
  input         io_in_hvien_LC52IE,
  input         io_in_hvien_LC53IE,
  input         io_in_hvien_LC54IE,
  input         io_in_hvien_LC55IE,
  input         io_in_hvien_LC56IE,
  input         io_in_hvien_LC57IE,
  input         io_in_hvien_LC58IE,
  input         io_in_hvien_LC59IE,
  input         io_in_hvien_LC60IE,
  input         io_in_hvien_LC61IE,
  input         io_in_hvien_LC62IE,
  input         io_in_hvien_LC63IE,
  input  [1:0]  io_in_mtvec_mode,
  input  [61:0] io_in_mtvec_addr,
  input  [1:0]  io_in_stvec_mode,
  input  [61:0] io_in_stvec_addr,
  input  [1:0]  io_in_vstvec_mode,
  input  [61:0] io_in_vstvec_addr,
  output [1:0]  io_out_entryPrivState_PRVM,
  output        io_out_entryPrivState_V,
  output        io_out_causeNO_Interrupt,
  output [62:0] io_out_causeNO_ExceptionCode,
  output [63:0] io_out_pcFromXtvec
);

  wire        hasIR = io_in_trapInfo_valid & io_in_trapInfo_bits_isInterrupt;
  wire [23:0] hasEXVec =
    io_in_trapInfo_valid & ~io_in_trapInfo_bits_isInterrupt
      ? io_in_trapInfo_bits_trapVec[23:0]
      : 24'h0;
  wire [62:0] hasIRVec = hasIR ? io_in_trapInfo_bits_intrVec[63:1] : 63'h0;
  wire        hasIRQinGroup_customHighest =
    |{hasIRVec[62], hasIRVec[30], hasIRVec[61:60], hasIRVec[29], hasIRVec[59]};
  wire        hasIRQinGroup_localHigh =
    |{hasIRVec[46],
      hasIRVec[22],
      hasIRVec[45:44],
      hasIRVec[21],
      hasIRVec[43:42],
      hasIRVec[20],
      hasIRVec[41:40],
      hasIRVec[19],
      hasIRVec[39]};
  wire        hasIRQinGroup_customMiddleHigh =
    |{hasIRVec[58], hasIRVec[28], hasIRVec[57:56], hasIRVec[27], hasIRVec[55]};
  wire        hasIRQinGroup_privArch =
    |{hasIRVec[10],
      hasIRVec[2],
      hasIRVec[6],
      hasIRVec[8],
      hasIRVec[0],
      hasIRVec[4],
      hasIRVec[11],
      hasIRVec[9],
      hasIRVec[1],
      hasIRVec[5],
      hasIRVec[12]};
  wire        hasIRQinGroup_customMiddleLow =
    |{hasIRVec[54], hasIRVec[26], hasIRVec[53:52], hasIRVec[25], hasIRVec[51]};
  wire        hasIRQinGroup_localLow =
    |{hasIRVec[38],
      hasIRVec[18],
      hasIRVec[37:36],
      hasIRVec[17],
      hasIRVec[35:34],
      hasIRVec[16],
      hasIRVec[33:32],
      hasIRVec[15],
      hasIRVec[31]};
  wire        hasIRQinGroup_customLowest =
    |{hasIRVec[50], hasIRVec[24], hasIRVec[49:48], hasIRVec[23], hasIRVec[47]};
  wire        _GEN =
    hasIRQinGroup_customHighest | hasIRQinGroup_localHigh
    | hasIRQinGroup_customMiddleHigh;
  wire        highestPrioIRVec_1 =
    ~_GEN & hasIRQinGroup_privArch
    & (&{~(hasIRVec[10]), ~(hasIRVec[2]), ~(hasIRVec[6]), ~(hasIRVec[8])}) & hasIRVec[0];
  wire        highestPrioIRVec_2 =
    ~_GEN & hasIRQinGroup_privArch
    & (&{~(hasIRVec[10]),
         ~(hasIRVec[2]),
         ~(hasIRVec[6]),
         ~(hasIRVec[8]),
         ~(hasIRVec[0]),
         ~(hasIRVec[4]),
         ~(hasIRVec[11]),
         ~(hasIRVec[9])}) & hasIRVec[1];
  wire        highestPrioIRVec_3 =
    ~_GEN & hasIRQinGroup_privArch & ~(hasIRVec[10]) & hasIRVec[2];
  wire        highestPrioIRVec_5 =
    ~_GEN & hasIRQinGroup_privArch
    & (&{~(hasIRVec[10]), ~(hasIRVec[2]), ~(hasIRVec[6]), ~(hasIRVec[8]), ~(hasIRVec[0])})
    & hasIRVec[4];
  wire        highestPrioIRVec_6 =
    ~_GEN & hasIRQinGroup_privArch
    & (&{~(hasIRVec[10]),
         ~(hasIRVec[2]),
         ~(hasIRVec[6]),
         ~(hasIRVec[8]),
         ~(hasIRVec[0]),
         ~(hasIRVec[4]),
         ~(hasIRVec[11]),
         ~(hasIRVec[9]),
         ~(hasIRVec[1])}) & hasIRVec[5];
  wire        highestPrioIRVec_7 =
    ~_GEN & hasIRQinGroup_privArch & (&{~(hasIRVec[10]), ~(hasIRVec[2])}) & hasIRVec[6];
  wire        highestPrioIRVec_9 =
    ~_GEN & hasIRQinGroup_privArch & (&{~(hasIRVec[10]), ~(hasIRVec[2]), ~(hasIRVec[6])})
    & hasIRVec[8];
  wire        highestPrioIRVec_10 =
    ~_GEN & hasIRQinGroup_privArch
    & (&{~(hasIRVec[10]),
         ~(hasIRVec[2]),
         ~(hasIRVec[6]),
         ~(hasIRVec[8]),
         ~(hasIRVec[0]),
         ~(hasIRVec[4]),
         ~(hasIRVec[11])}) & hasIRVec[9];
  wire        highestPrioIRVec_11 = ~_GEN & hasIRQinGroup_privArch & hasIRVec[10];
  wire        highestPrioIRVec_12 =
    ~_GEN & hasIRQinGroup_privArch
    & (&{~(hasIRVec[10]),
         ~(hasIRVec[2]),
         ~(hasIRVec[6]),
         ~(hasIRVec[8]),
         ~(hasIRVec[0]),
         ~(hasIRVec[4])}) & hasIRVec[11];
  wire        highestPrioIRVec_13 =
    ~_GEN & hasIRQinGroup_privArch
    & (&{~(hasIRVec[10]),
         ~(hasIRVec[2]),
         ~(hasIRVec[6]),
         ~(hasIRVec[8]),
         ~(hasIRVec[0]),
         ~(hasIRVec[4]),
         ~(hasIRVec[11]),
         ~(hasIRVec[9]),
         ~(hasIRVec[1]),
         ~(hasIRVec[5])}) & hasIRVec[12];
  wire        _GEN_0 =
    hasIRQinGroup_customHighest | hasIRQinGroup_localHigh | hasIRQinGroup_customMiddleHigh
    | hasIRQinGroup_privArch | hasIRQinGroup_customMiddleLow;
  wire        highestPrioIRVec_16 =
    ~_GEN_0 & hasIRQinGroup_localLow
    & (&{~(hasIRVec[38]),
         ~(hasIRVec[18]),
         ~(hasIRVec[37]),
         ~(hasIRVec[36]),
         ~(hasIRVec[17]),
         ~(hasIRVec[35]),
         ~(hasIRVec[34]),
         ~(hasIRVec[16]),
         ~(hasIRVec[33]),
         ~(hasIRVec[32])}) & hasIRVec[15];
  wire        highestPrioIRVec_17 =
    ~_GEN_0 & hasIRQinGroup_localLow
    & (&{~(hasIRVec[38]),
         ~(hasIRVec[18]),
         ~(hasIRVec[37]),
         ~(hasIRVec[36]),
         ~(hasIRVec[17]),
         ~(hasIRVec[35]),
         ~(hasIRVec[34])}) & hasIRVec[16];
  wire        highestPrioIRVec_18 =
    ~_GEN_0 & hasIRQinGroup_localLow
    & (&{~(hasIRVec[38]), ~(hasIRVec[18]), ~(hasIRVec[37]), ~(hasIRVec[36])})
    & hasIRVec[17];
  wire        highestPrioIRVec_19 =
    ~_GEN_0 & hasIRQinGroup_localLow & ~(hasIRVec[38]) & hasIRVec[18];
  wire        highestPrioIRVec_20 =
    ~hasIRQinGroup_customHighest & hasIRQinGroup_localHigh
    & (&{~(hasIRVec[46]),
         ~(hasIRVec[22]),
         ~(hasIRVec[45]),
         ~(hasIRVec[44]),
         ~(hasIRVec[21]),
         ~(hasIRVec[43]),
         ~(hasIRVec[42]),
         ~(hasIRVec[20]),
         ~(hasIRVec[41]),
         ~(hasIRVec[40])}) & hasIRVec[19];
  wire        highestPrioIRVec_21 =
    ~hasIRQinGroup_customHighest & hasIRQinGroup_localHigh
    & (&{~(hasIRVec[46]),
         ~(hasIRVec[22]),
         ~(hasIRVec[45]),
         ~(hasIRVec[44]),
         ~(hasIRVec[21]),
         ~(hasIRVec[43]),
         ~(hasIRVec[42])}) & hasIRVec[20];
  wire        highestPrioIRVec_22 =
    ~hasIRQinGroup_customHighest & hasIRQinGroup_localHigh
    & (&{~(hasIRVec[46]), ~(hasIRVec[22]), ~(hasIRVec[45]), ~(hasIRVec[44])})
    & hasIRVec[21];
  wire        highestPrioIRVec_23 =
    ~hasIRQinGroup_customHighest & hasIRQinGroup_localHigh & ~(hasIRVec[46])
    & hasIRVec[22];
  wire        _GEN_1 =
    hasIRQinGroup_customHighest | hasIRQinGroup_localHigh | hasIRQinGroup_customMiddleHigh
    | hasIRQinGroup_privArch | hasIRQinGroup_customMiddleLow | hasIRQinGroup_localLow;
  wire        highestPrioIRVec_24 =
    ~_GEN_1 & hasIRQinGroup_customLowest
    & (&{~(hasIRVec[50]), ~(hasIRVec[24]), ~(hasIRVec[49]), ~(hasIRVec[48])})
    & hasIRVec[23];
  wire        highestPrioIRVec_25 =
    ~_GEN_1 & hasIRQinGroup_customLowest & ~(hasIRVec[50]) & hasIRVec[24];
  wire        _GEN_2 =
    hasIRQinGroup_customHighest | hasIRQinGroup_localHigh | hasIRQinGroup_customMiddleHigh
    | hasIRQinGroup_privArch;
  wire        highestPrioIRVec_26 =
    ~_GEN_2 & hasIRQinGroup_customMiddleLow
    & (&{~(hasIRVec[54]), ~(hasIRVec[26]), ~(hasIRVec[53]), ~(hasIRVec[52])})
    & hasIRVec[25];
  wire        highestPrioIRVec_27 =
    ~_GEN_2 & hasIRQinGroup_customMiddleLow & ~(hasIRVec[54]) & hasIRVec[26];
  wire        _GEN_3 = hasIRQinGroup_customHighest | hasIRQinGroup_localHigh;
  wire        highestPrioIRVec_28 =
    ~_GEN_3 & hasIRQinGroup_customMiddleHigh
    & (&{~(hasIRVec[58]), ~(hasIRVec[28]), ~(hasIRVec[57]), ~(hasIRVec[56])})
    & hasIRVec[27];
  wire        highestPrioIRVec_29 =
    ~_GEN_3 & hasIRQinGroup_customMiddleHigh & ~(hasIRVec[58]) & hasIRVec[28];
  wire        highestPrioIRVec_30 =
    hasIRQinGroup_customHighest
    & (&{~(hasIRVec[62]), ~(hasIRVec[30]), ~(hasIRVec[61]), ~(hasIRVec[60])})
    & hasIRVec[29];
  wire        highestPrioIRVec_31 =
    hasIRQinGroup_customHighest & ~(hasIRVec[62]) & hasIRVec[30];
  wire        highestPrioIRVec_32 =
    ~_GEN_0 & hasIRQinGroup_localLow
    & (&{~(hasIRVec[38]),
         ~(hasIRVec[18]),
         ~(hasIRVec[37]),
         ~(hasIRVec[36]),
         ~(hasIRVec[17]),
         ~(hasIRVec[35]),
         ~(hasIRVec[34]),
         ~(hasIRVec[16]),
         ~(hasIRVec[33]),
         ~(hasIRVec[32]),
         ~(hasIRVec[15])}) & hasIRVec[31];
  wire        highestPrioIRVec_33 =
    ~_GEN_0 & hasIRQinGroup_localLow
    & (&{~(hasIRVec[38]),
         ~(hasIRVec[18]),
         ~(hasIRVec[37]),
         ~(hasIRVec[36]),
         ~(hasIRVec[17]),
         ~(hasIRVec[35]),
         ~(hasIRVec[34]),
         ~(hasIRVec[16]),
         ~(hasIRVec[33])}) & hasIRVec[32];
  wire        highestPrioIRVec_34 =
    ~_GEN_0 & hasIRQinGroup_localLow
    & (&{~(hasIRVec[38]),
         ~(hasIRVec[18]),
         ~(hasIRVec[37]),
         ~(hasIRVec[36]),
         ~(hasIRVec[17]),
         ~(hasIRVec[35]),
         ~(hasIRVec[34]),
         ~(hasIRVec[16])}) & hasIRVec[33];
  wire        highestPrioIRVec_35 =
    ~_GEN_0 & hasIRQinGroup_localLow
    & (&{~(hasIRVec[38]),
         ~(hasIRVec[18]),
         ~(hasIRVec[37]),
         ~(hasIRVec[36]),
         ~(hasIRVec[17]),
         ~(hasIRVec[35])}) & hasIRVec[34];
  wire        highestPrioIRVec_36 =
    ~_GEN_0 & hasIRQinGroup_localLow
    & (&{~(hasIRVec[38]),
         ~(hasIRVec[18]),
         ~(hasIRVec[37]),
         ~(hasIRVec[36]),
         ~(hasIRVec[17])}) & hasIRVec[35];
  wire        highestPrioIRVec_37 =
    ~_GEN_0 & hasIRQinGroup_localLow
    & (&{~(hasIRVec[38]), ~(hasIRVec[18]), ~(hasIRVec[37])}) & hasIRVec[36];
  wire        highestPrioIRVec_38 =
    ~_GEN_0 & hasIRQinGroup_localLow & (&{~(hasIRVec[38]), ~(hasIRVec[18])})
    & hasIRVec[37];
  wire        highestPrioIRVec_39 = ~_GEN_0 & hasIRQinGroup_localLow & hasIRVec[38];
  wire        highestPrioIRVec_40 =
    ~hasIRQinGroup_customHighest & hasIRQinGroup_localHigh
    & (&{~(hasIRVec[46]),
         ~(hasIRVec[22]),
         ~(hasIRVec[45]),
         ~(hasIRVec[44]),
         ~(hasIRVec[21]),
         ~(hasIRVec[43]),
         ~(hasIRVec[42]),
         ~(hasIRVec[20]),
         ~(hasIRVec[41]),
         ~(hasIRVec[40]),
         ~(hasIRVec[19])}) & hasIRVec[39];
  wire        highestPrioIRVec_41 =
    ~hasIRQinGroup_customHighest & hasIRQinGroup_localHigh
    & (&{~(hasIRVec[46]),
         ~(hasIRVec[22]),
         ~(hasIRVec[45]),
         ~(hasIRVec[44]),
         ~(hasIRVec[21]),
         ~(hasIRVec[43]),
         ~(hasIRVec[42]),
         ~(hasIRVec[20]),
         ~(hasIRVec[41])}) & hasIRVec[40];
  wire        highestPrioIRVec_42 =
    ~hasIRQinGroup_customHighest & hasIRQinGroup_localHigh
    & (&{~(hasIRVec[46]),
         ~(hasIRVec[22]),
         ~(hasIRVec[45]),
         ~(hasIRVec[44]),
         ~(hasIRVec[21]),
         ~(hasIRVec[43]),
         ~(hasIRVec[42]),
         ~(hasIRVec[20])}) & hasIRVec[41];
  wire        highestPrioIRVec_43 =
    ~hasIRQinGroup_customHighest & hasIRQinGroup_localHigh
    & (&{~(hasIRVec[46]),
         ~(hasIRVec[22]),
         ~(hasIRVec[45]),
         ~(hasIRVec[44]),
         ~(hasIRVec[21]),
         ~(hasIRVec[43])}) & hasIRVec[42];
  wire        highestPrioIRVec_44 =
    ~hasIRQinGroup_customHighest & hasIRQinGroup_localHigh
    & (&{~(hasIRVec[46]),
         ~(hasIRVec[22]),
         ~(hasIRVec[45]),
         ~(hasIRVec[44]),
         ~(hasIRVec[21])}) & hasIRVec[43];
  wire        highestPrioIRVec_45 =
    ~hasIRQinGroup_customHighest & hasIRQinGroup_localHigh
    & (&{~(hasIRVec[46]), ~(hasIRVec[22]), ~(hasIRVec[45])}) & hasIRVec[44];
  wire        highestPrioIRVec_46 =
    ~hasIRQinGroup_customHighest & hasIRQinGroup_localHigh
    & (&{~(hasIRVec[46]), ~(hasIRVec[22])}) & hasIRVec[45];
  wire        highestPrioIRVec_47 =
    ~hasIRQinGroup_customHighest & hasIRQinGroup_localHigh & hasIRVec[46];
  wire        highestPrioIRVec_48 =
    ~_GEN_1 & hasIRQinGroup_customLowest
    & (&{~(hasIRVec[50]),
         ~(hasIRVec[24]),
         ~(hasIRVec[49]),
         ~(hasIRVec[48]),
         ~(hasIRVec[23])}) & hasIRVec[47];
  wire        highestPrioIRVec_49 =
    ~_GEN_1 & hasIRQinGroup_customLowest
    & (&{~(hasIRVec[50]), ~(hasIRVec[24]), ~(hasIRVec[49])}) & hasIRVec[48];
  wire        highestPrioIRVec_50 =
    ~_GEN_1 & hasIRQinGroup_customLowest & (&{~(hasIRVec[50]), ~(hasIRVec[24])})
    & hasIRVec[49];
  wire        highestPrioIRVec_51 = ~_GEN_1 & hasIRQinGroup_customLowest & hasIRVec[50];
  wire        highestPrioIRVec_52 =
    ~_GEN_2 & hasIRQinGroup_customMiddleLow
    & (&{~(hasIRVec[54]),
         ~(hasIRVec[26]),
         ~(hasIRVec[53]),
         ~(hasIRVec[52]),
         ~(hasIRVec[25])}) & hasIRVec[51];
  wire        highestPrioIRVec_53 =
    ~_GEN_2 & hasIRQinGroup_customMiddleLow
    & (&{~(hasIRVec[54]), ~(hasIRVec[26]), ~(hasIRVec[53])}) & hasIRVec[52];
  wire        highestPrioIRVec_54 =
    ~_GEN_2 & hasIRQinGroup_customMiddleLow & (&{~(hasIRVec[54]), ~(hasIRVec[26])})
    & hasIRVec[53];
  wire        highestPrioIRVec_55 =
    ~_GEN_2 & hasIRQinGroup_customMiddleLow & hasIRVec[54];
  wire        highestPrioIRVec_56 =
    ~_GEN_3 & hasIRQinGroup_customMiddleHigh
    & (&{~(hasIRVec[58]),
         ~(hasIRVec[28]),
         ~(hasIRVec[57]),
         ~(hasIRVec[56]),
         ~(hasIRVec[27])}) & hasIRVec[55];
  wire        highestPrioIRVec_57 =
    ~_GEN_3 & hasIRQinGroup_customMiddleHigh
    & (&{~(hasIRVec[58]), ~(hasIRVec[28]), ~(hasIRVec[57])}) & hasIRVec[56];
  wire        highestPrioIRVec_58 =
    ~_GEN_3 & hasIRQinGroup_customMiddleHigh & (&{~(hasIRVec[58]), ~(hasIRVec[28])})
    & hasIRVec[57];
  wire        highestPrioIRVec_59 =
    ~_GEN_3 & hasIRQinGroup_customMiddleHigh & hasIRVec[58];
  wire        highestPrioIRVec_60 =
    hasIRQinGroup_customHighest
    & (&{~(hasIRVec[62]),
         ~(hasIRVec[30]),
         ~(hasIRVec[61]),
         ~(hasIRVec[60]),
         ~(hasIRVec[29])}) & hasIRVec[59];
  wire        highestPrioIRVec_61 =
    hasIRQinGroup_customHighest & (&{~(hasIRVec[62]), ~(hasIRVec[30]), ~(hasIRVec[61])})
    & hasIRVec[60];
  wire        highestPrioIRVec_62 =
    hasIRQinGroup_customHighest & (&{~(hasIRVec[62]), ~(hasIRVec[30])}) & hasIRVec[61];
  wire        highestPrioIRVec_63 = hasIRQinGroup_customHighest & hasIRVec[62];
  wire        highestPrioEXVec_1 =
    (&{~(hasEXVec[3]), ~(hasEXVec[12]), ~(hasEXVec[20])}) & hasEXVec[1];
  wire        highestPrioEXVec_2 =
    (&{~(hasEXVec[3]), ~(hasEXVec[12]), ~(hasEXVec[20]), ~(hasEXVec[1])}) & hasEXVec[2];
  wire        highestPrioEXVec_4 =
    (&{~(hasEXVec[3]),
       ~(hasEXVec[12]),
       ~(hasEXVec[20]),
       ~(hasEXVec[1]),
       ~(hasEXVec[2]),
       ~(hasEXVec[22]),
       ~(hasEXVec[0]),
       ~(hasEXVec[11]),
       ~(hasEXVec[9]),
       ~(hasEXVec[10]),
       ~(hasEXVec[8]),
       ~(hasEXVec[6])}) & hasEXVec[4];
  wire        highestPrioEXVec_5 =
    (&{~(hasEXVec[3]),
       ~(hasEXVec[12]),
       ~(hasEXVec[20]),
       ~(hasEXVec[1]),
       ~(hasEXVec[2]),
       ~(hasEXVec[22]),
       ~(hasEXVec[0]),
       ~(hasEXVec[11]),
       ~(hasEXVec[9]),
       ~(hasEXVec[10]),
       ~(hasEXVec[8]),
       ~(hasEXVec[6]),
       ~(hasEXVec[4]),
       ~(hasEXVec[15]),
       ~(hasEXVec[13]),
       ~(hasEXVec[23]),
       ~(hasEXVec[21]),
       ~(hasEXVec[7])}) & hasEXVec[5];
  wire        highestPrioEXVec_6 =
    (&{~(hasEXVec[3]),
       ~(hasEXVec[12]),
       ~(hasEXVec[20]),
       ~(hasEXVec[1]),
       ~(hasEXVec[2]),
       ~(hasEXVec[22]),
       ~(hasEXVec[0]),
       ~(hasEXVec[11]),
       ~(hasEXVec[9]),
       ~(hasEXVec[10]),
       ~(hasEXVec[8])}) & hasEXVec[6];
  wire        highestPrioEXVec_7 =
    (&{~(hasEXVec[3]),
       ~(hasEXVec[12]),
       ~(hasEXVec[20]),
       ~(hasEXVec[1]),
       ~(hasEXVec[2]),
       ~(hasEXVec[22]),
       ~(hasEXVec[0]),
       ~(hasEXVec[11]),
       ~(hasEXVec[9]),
       ~(hasEXVec[10]),
       ~(hasEXVec[8]),
       ~(hasEXVec[6]),
       ~(hasEXVec[4]),
       ~(hasEXVec[15]),
       ~(hasEXVec[13]),
       ~(hasEXVec[23]),
       ~(hasEXVec[21])}) & hasEXVec[7];
  wire        highestPrioEXVec_8 =
    (&{~(hasEXVec[3]),
       ~(hasEXVec[12]),
       ~(hasEXVec[20]),
       ~(hasEXVec[1]),
       ~(hasEXVec[2]),
       ~(hasEXVec[22]),
       ~(hasEXVec[0]),
       ~(hasEXVec[11]),
       ~(hasEXVec[9]),
       ~(hasEXVec[10])}) & hasEXVec[8];
  wire        highestPrioEXVec_9 =
    (&{~(hasEXVec[3]),
       ~(hasEXVec[12]),
       ~(hasEXVec[20]),
       ~(hasEXVec[1]),
       ~(hasEXVec[2]),
       ~(hasEXVec[22]),
       ~(hasEXVec[0]),
       ~(hasEXVec[11])}) & hasEXVec[9];
  wire        highestPrioEXVec_10 =
    (&{~(hasEXVec[3]),
       ~(hasEXVec[12]),
       ~(hasEXVec[20]),
       ~(hasEXVec[1]),
       ~(hasEXVec[2]),
       ~(hasEXVec[22]),
       ~(hasEXVec[0]),
       ~(hasEXVec[11]),
       ~(hasEXVec[9])}) & hasEXVec[10];
  wire        highestPrioEXVec_11 =
    (&{~(hasEXVec[3]),
       ~(hasEXVec[12]),
       ~(hasEXVec[20]),
       ~(hasEXVec[1]),
       ~(hasEXVec[2]),
       ~(hasEXVec[22]),
       ~(hasEXVec[0])}) & hasEXVec[11];
  wire        highestPrioEXVec_12 = ~(hasEXVec[3]) & hasEXVec[12];
  wire        highestPrioEXVec_13 =
    (&{~(hasEXVec[3]),
       ~(hasEXVec[12]),
       ~(hasEXVec[20]),
       ~(hasEXVec[1]),
       ~(hasEXVec[2]),
       ~(hasEXVec[22]),
       ~(hasEXVec[0]),
       ~(hasEXVec[11]),
       ~(hasEXVec[9]),
       ~(hasEXVec[10]),
       ~(hasEXVec[8]),
       ~(hasEXVec[6]),
       ~(hasEXVec[4]),
       ~(hasEXVec[15])}) & hasEXVec[13];
  wire        highestPrioEXVec_15 =
    (&{~(hasEXVec[3]),
       ~(hasEXVec[12]),
       ~(hasEXVec[20]),
       ~(hasEXVec[1]),
       ~(hasEXVec[2]),
       ~(hasEXVec[22]),
       ~(hasEXVec[0]),
       ~(hasEXVec[11]),
       ~(hasEXVec[9]),
       ~(hasEXVec[10]),
       ~(hasEXVec[8]),
       ~(hasEXVec[6]),
       ~(hasEXVec[4])}) & hasEXVec[15];
  wire        highestPrioEXVec_20 = (&{~(hasEXVec[3]), ~(hasEXVec[12])}) & hasEXVec[20];
  wire        highestPrioEXVec_21 =
    (&{~(hasEXVec[3]),
       ~(hasEXVec[12]),
       ~(hasEXVec[20]),
       ~(hasEXVec[1]),
       ~(hasEXVec[2]),
       ~(hasEXVec[22]),
       ~(hasEXVec[0]),
       ~(hasEXVec[11]),
       ~(hasEXVec[9]),
       ~(hasEXVec[10]),
       ~(hasEXVec[8]),
       ~(hasEXVec[6]),
       ~(hasEXVec[4]),
       ~(hasEXVec[15]),
       ~(hasEXVec[13]),
       ~(hasEXVec[23])}) & hasEXVec[21];
  wire        highestPrioEXVec_22 =
    (&{~(hasEXVec[3]), ~(hasEXVec[12]), ~(hasEXVec[20]), ~(hasEXVec[1]), ~(hasEXVec[2])})
    & hasEXVec[22];
  wire        highestPrioEXVec_23 =
    (&{~(hasEXVec[3]),
       ~(hasEXVec[12]),
       ~(hasEXVec[20]),
       ~(hasEXVec[1]),
       ~(hasEXVec[2]),
       ~(hasEXVec[22]),
       ~(hasEXVec[0]),
       ~(hasEXVec[11]),
       ~(hasEXVec[9]),
       ~(hasEXVec[10]),
       ~(hasEXVec[8]),
       ~(hasEXVec[6]),
       ~(hasEXVec[4]),
       ~(hasEXVec[15]),
       ~(hasEXVec[13])}) & hasEXVec[23];
  wire [63:0] mIRVec =
    {highestPrioIRVec_63,
     highestPrioIRVec_62,
     highestPrioIRVec_61,
     highestPrioIRVec_60,
     highestPrioIRVec_59,
     highestPrioIRVec_58,
     highestPrioIRVec_57,
     highestPrioIRVec_56,
     highestPrioIRVec_55,
     highestPrioIRVec_54,
     highestPrioIRVec_53,
     highestPrioIRVec_52,
     highestPrioIRVec_51,
     highestPrioIRVec_50,
     highestPrioIRVec_49,
     highestPrioIRVec_48,
     highestPrioIRVec_47,
     highestPrioIRVec_46,
     highestPrioIRVec_45,
     highestPrioIRVec_44,
     highestPrioIRVec_43,
     highestPrioIRVec_42,
     highestPrioIRVec_41,
     highestPrioIRVec_40,
     highestPrioIRVec_39,
     highestPrioIRVec_38,
     highestPrioIRVec_37,
     highestPrioIRVec_36,
     highestPrioIRVec_35,
     highestPrioIRVec_34,
     highestPrioIRVec_33,
     highestPrioIRVec_32,
     highestPrioIRVec_31,
     highestPrioIRVec_30,
     highestPrioIRVec_29,
     highestPrioIRVec_28,
     highestPrioIRVec_27,
     highestPrioIRVec_26,
     highestPrioIRVec_25,
     highestPrioIRVec_24,
     highestPrioIRVec_23,
     highestPrioIRVec_22,
     highestPrioIRVec_21,
     highestPrioIRVec_20,
     highestPrioIRVec_19,
     highestPrioIRVec_18,
     highestPrioIRVec_17,
     highestPrioIRVec_16,
     2'h0,
     highestPrioIRVec_13,
     highestPrioIRVec_12,
     highestPrioIRVec_11,
     highestPrioIRVec_10,
     highestPrioIRVec_9,
     1'h0,
     highestPrioIRVec_7,
     highestPrioIRVec_6,
     highestPrioIRVec_5,
     1'h0,
     highestPrioIRVec_3,
     highestPrioIRVec_2,
     highestPrioIRVec_1,
     1'h0};
  wire [62:0] hsIRVec =
    mIRVec[63:1]
    & {50'h0,
       io_in_mideleg_LCOFI,
       3'h5,
       io_in_mideleg_SEI,
       3'h1,
       io_in_mideleg_STI,
       3'h1,
       io_in_mideleg_SSI} | mIRVec[63:1]
    & {io_in_mvien_LC63IE,
       io_in_mvien_LC62IE,
       io_in_mvien_LC61IE,
       io_in_mvien_LC60IE,
       io_in_mvien_LC59IE,
       io_in_mvien_LC58IE,
       io_in_mvien_LC57IE,
       io_in_mvien_LC56IE,
       io_in_mvien_LC55IE,
       io_in_mvien_LC54IE,
       io_in_mvien_LC53IE,
       io_in_mvien_LC52IE,
       io_in_mvien_LC51IE,
       io_in_mvien_LC50IE,
       io_in_mvien_LC49IE,
       io_in_mvien_LC48IE,
       io_in_mvien_LC47IE,
       io_in_mvien_LC46IE,
       io_in_mvien_LC45IE,
       io_in_mvien_LC44IE,
       io_in_mvien_HPRASEIE,
       io_in_mvien_LC42IE,
       io_in_mvien_LC41IE,
       io_in_mvien_LC40IE,
       io_in_mvien_LC39IE,
       io_in_mvien_LC38IE,
       io_in_mvien_LC37IE,
       io_in_mvien_LC36IE,
       io_in_mvien_LPRASEIE,
       io_in_mvien_LC34IE,
       io_in_mvien_LC33IE,
       io_in_mvien_LC32IE,
       io_in_mvien_LC31IE,
       io_in_mvien_LC30IE,
       io_in_mvien_LC29IE,
       io_in_mvien_LC28IE,
       io_in_mvien_LC27IE,
       io_in_mvien_LC26IE,
       io_in_mvien_LC25IE,
       io_in_mvien_LC24IE,
       io_in_mvien_LC23IE,
       io_in_mvien_LC22IE,
       io_in_mvien_LC21IE,
       io_in_mvien_LC20IE,
       io_in_mvien_LC19IE,
       io_in_mvien_LC18IE,
       io_in_mvien_LC17IE,
       io_in_mvien_LC16IE,
       io_in_mvien_LC15IE,
       io_in_mvien_LC14IE,
       io_in_mvien_LCOFIE,
       3'h0,
       io_in_mvien_SEIE,
       7'h0,
       io_in_mvien_SSIE}
    & {50'h3FFFFFFFFFFFF,
       ~io_in_mideleg_LCOFI,
       3'h2,
       ~io_in_mideleg_SEI,
       3'h6,
       ~io_in_mideleg_STI,
       3'h6,
       ~io_in_mideleg_SSI};
  wire [61:0] vsIRVec =
    hsIRVec[62:1]
    & {50'h0,
       io_in_hideleg_LCOFI,
       2'h0,
       io_in_hideleg_VSEI,
       3'h0,
       io_in_hideleg_VSTI,
       3'h0,
       io_in_hideleg_VSSI} | hsIRVec[62:1]
    & {io_in_hvien_LC63IE,
       io_in_hvien_LC62IE,
       io_in_hvien_LC61IE,
       io_in_hvien_LC60IE,
       io_in_hvien_LC59IE,
       io_in_hvien_LC58IE,
       io_in_hvien_LC57IE,
       io_in_hvien_LC56IE,
       io_in_hvien_LC55IE,
       io_in_hvien_LC54IE,
       io_in_hvien_LC53IE,
       io_in_hvien_LC52IE,
       io_in_hvien_LC51IE,
       io_in_hvien_LC50IE,
       io_in_hvien_LC49IE,
       io_in_hvien_LC48IE,
       io_in_hvien_LC47IE,
       io_in_hvien_LC46IE,
       io_in_hvien_LC45IE,
       io_in_hvien_LC44IE,
       io_in_hvien_HPRASEIE,
       io_in_hvien_LC42IE,
       io_in_hvien_LC41IE,
       io_in_hvien_LC40IE,
       io_in_hvien_LC39IE,
       io_in_hvien_LC38IE,
       io_in_hvien_LC37IE,
       io_in_hvien_LC36IE,
       io_in_hvien_LPRASEIE,
       io_in_hvien_LC34IE,
       io_in_hvien_LC33IE,
       io_in_hvien_LC32IE,
       io_in_hvien_LC31IE,
       io_in_hvien_LC30IE,
       io_in_hvien_LC29IE,
       io_in_hvien_LC28IE,
       io_in_hvien_LC27IE,
       io_in_hvien_LC26IE,
       io_in_hvien_LC25IE,
       io_in_hvien_LC24IE,
       io_in_hvien_LC23IE,
       io_in_hvien_LC22IE,
       io_in_hvien_LC21IE,
       io_in_hvien_LC20IE,
       io_in_hvien_LC19IE,
       io_in_hvien_LC18IE,
       io_in_hvien_LC17IE,
       io_in_hvien_LC16IE,
       io_in_hvien_LC15IE,
       io_in_hvien_LC14IE,
       io_in_hvien_LCOFIE,
       11'h0}
    & {50'h3FFFFFFFFFFFF,
       ~io_in_hideleg_LCOFI,
       2'h3,
       ~io_in_hideleg_VSEI,
       3'h7,
       ~io_in_hideleg_VSTI,
       3'h7,
       ~io_in_hideleg_VSSI};
  wire [23:0] hsEXVec =
    {highestPrioEXVec_23,
     highestPrioEXVec_22,
     highestPrioEXVec_21,
     highestPrioEXVec_20,
     4'h0,
     highestPrioEXVec_15,
     1'h0,
     highestPrioEXVec_13,
     highestPrioEXVec_12,
     highestPrioEXVec_11,
     highestPrioEXVec_10,
     highestPrioEXVec_9,
     highestPrioEXVec_8,
     highestPrioEXVec_7,
     highestPrioEXVec_6,
     highestPrioEXVec_5,
     highestPrioEXVec_4,
     hasEXVec[3],
     highestPrioEXVec_2,
     highestPrioEXVec_1,
     (&{~(hasEXVec[3]),
        ~(hasEXVec[12]),
        ~(hasEXVec[20]),
        ~(hasEXVec[1]),
        ~(hasEXVec[2]),
        ~(hasEXVec[22])}) & hasEXVec[0]}
    & {io_in_medeleg_EX_SGPF,
       io_in_medeleg_EX_VI,
       io_in_medeleg_EX_LGPF,
       io_in_medeleg_EX_IGPF,
       4'h0,
       io_in_medeleg_EX_SPF,
       1'h0,
       io_in_medeleg_EX_LPF,
       io_in_medeleg_EX_IPF,
       1'h0,
       io_in_medeleg_EX_VSCALL,
       io_in_medeleg_EX_HSCALL,
       io_in_medeleg_EX_UCALL,
       io_in_medeleg_EX_SAF,
       io_in_medeleg_EX_SAM,
       io_in_medeleg_EX_LAF,
       io_in_medeleg_EX_LAM,
       1'h0,
       io_in_medeleg_EX_II,
       io_in_medeleg_EX_IAF,
       io_in_medeleg_EX_IAM};
  wire [15:0] vsEXVec =
    hsEXVec[15:0]
    & {io_in_hedeleg_EX_SPF,
       1'h0,
       io_in_hedeleg_EX_LPF,
       io_in_hedeleg_EX_IPF,
       3'h0,
       io_in_hedeleg_EX_UCALL,
       io_in_hedeleg_EX_SAF,
       io_in_hedeleg_EX_SAM,
       io_in_hedeleg_EX_LAF,
       io_in_hedeleg_EX_LAM,
       io_in_hedeleg_EX_BP,
       io_in_hedeleg_EX_II,
       io_in_hedeleg_EX_IAF,
       io_in_hedeleg_EX_IAM};
  wire        handleTrapUnderHS_v_PrvmIsM = &io_in_privState_PRVM;
  wire        handleTrapUnderHS_isModeM = handleTrapUnderHS_v_PrvmIsM;
  wire        handleTrapUnderHS =
    ~handleTrapUnderHS_isModeM
    & ((|{hsEXVec[23:20], hsEXVec[15], hsEXVec[13:12], hsEXVec[10:4], hsEXVec[2:0]})
       | (|{hsIRVec[62:11], hsIRVec[9:8], hsIRVec[5:4], hsIRVec[1:0]}));
  wire        handleTrapUnderVS =
    io_in_privState_V
    & ((|{vsEXVec[15], vsEXVec[13:12], vsEXVec[8:4], vsEXVec[2:0]})
       | (|{vsIRVec[61:11], vsIRVec[8], vsIRVec[4], vsIRVec[0]}));
  wire        _GEN_4 = highestPrioEXVec_22 | highestPrioEXVec_6;
  wire        _GEN_5 = highestPrioEXVec_15 | highestPrioEXVec_23 | highestPrioEXVec_7;
  wire        _GEN_6 = highestPrioEXVec_13 | highestPrioEXVec_21 | highestPrioEXVec_5;
  wire [2:0]  _exceptionRegular_T_7 =
    {_GEN_5, _GEN_4, _GEN_6}
    | {highestPrioEXVec_11 | hasEXVec[3],
       highestPrioEXVec_10 | highestPrioEXVec_2,
       highestPrioEXVec_9 | highestPrioEXVec_1};
  wire        _GEN_7 = highestPrioIRVec_63 | highestPrioIRVec_31;
  wire        _GEN_8 = highestPrioIRVec_62 | highestPrioIRVec_30;
  wire        _GEN_9 = highestPrioIRVec_61 | highestPrioIRVec_29;
  wire        _GEN_10 = highestPrioIRVec_60 | highestPrioIRVec_28;
  wire        _GEN_11 = highestPrioIRVec_59 | highestPrioIRVec_27;
  wire        _GEN_12 = highestPrioIRVec_58 | highestPrioIRVec_26;
  wire        _GEN_13 = highestPrioIRVec_57 | highestPrioIRVec_25;
  wire        _GEN_14 = highestPrioIRVec_56 | highestPrioIRVec_24;
  wire        _GEN_15 = highestPrioIRVec_55 | highestPrioIRVec_23;
  wire        _GEN_16 = highestPrioIRVec_54 | highestPrioIRVec_22;
  wire        _GEN_17 = highestPrioIRVec_53 | highestPrioIRVec_21;
  wire        _GEN_18 = highestPrioIRVec_52 | highestPrioIRVec_20;
  wire        _GEN_19 = highestPrioIRVec_51 | highestPrioIRVec_19;
  wire        _GEN_20 = highestPrioIRVec_50 | highestPrioIRVec_18;
  wire        _GEN_21 = highestPrioIRVec_49 | highestPrioIRVec_17;
  wire [14:0] _interruptNO_T_3 =
    {_GEN_7,
     _GEN_8,
     _GEN_9,
     _GEN_10,
     _GEN_11,
     _GEN_12,
     _GEN_13,
     _GEN_14,
     _GEN_15,
     _GEN_16,
     _GEN_17,
     _GEN_18,
     _GEN_19,
     _GEN_20,
     _GEN_21}
    | {highestPrioIRVec_47,
       highestPrioIRVec_46,
       highestPrioIRVec_45 | highestPrioIRVec_13,
       highestPrioIRVec_44 | highestPrioIRVec_12,
       highestPrioIRVec_43 | highestPrioIRVec_11,
       highestPrioIRVec_42 | highestPrioIRVec_10,
       highestPrioIRVec_41 | highestPrioIRVec_9,
       highestPrioIRVec_40,
       highestPrioIRVec_39 | highestPrioIRVec_7,
       highestPrioIRVec_38 | highestPrioIRVec_6,
       highestPrioIRVec_37 | highestPrioIRVec_5,
       highestPrioIRVec_36,
       highestPrioIRVec_35 | highestPrioIRVec_3,
       highestPrioIRVec_34 | highestPrioIRVec_2,
       highestPrioIRVec_33 | highestPrioIRVec_1};
  wire [6:0]  _interruptNO_T_5 = _interruptNO_T_3[14:8] | _interruptNO_T_3[6:0];
  wire [2:0]  _interruptNO_T_7 = _interruptNO_T_5[6:4] | _interruptNO_T_5[2:0];
  wire [5:0]  interruptNO =
    {|{highestPrioIRVec_63,
       highestPrioIRVec_62,
       highestPrioIRVec_61,
       highestPrioIRVec_60,
       highestPrioIRVec_59,
       highestPrioIRVec_58,
       highestPrioIRVec_57,
       highestPrioIRVec_56,
       highestPrioIRVec_55,
       highestPrioIRVec_54,
       highestPrioIRVec_53,
       highestPrioIRVec_52,
       highestPrioIRVec_51,
       highestPrioIRVec_50,
       highestPrioIRVec_49,
       highestPrioIRVec_48,
       highestPrioIRVec_47,
       highestPrioIRVec_46,
       highestPrioIRVec_45,
       highestPrioIRVec_44,
       highestPrioIRVec_43,
       highestPrioIRVec_42,
       highestPrioIRVec_41,
       highestPrioIRVec_40,
       highestPrioIRVec_39,
       highestPrioIRVec_38,
       highestPrioIRVec_37,
       highestPrioIRVec_36,
       highestPrioIRVec_35,
       highestPrioIRVec_34,
       highestPrioIRVec_33,
       highestPrioIRVec_32},
     |{_GEN_7,
       _GEN_8,
       _GEN_9,
       _GEN_10,
       _GEN_11,
       _GEN_12,
       _GEN_13,
       _GEN_14,
       _GEN_15,
       _GEN_16,
       _GEN_17,
       _GEN_18,
       _GEN_19,
       _GEN_20,
       _GEN_21,
       highestPrioIRVec_48 | highestPrioIRVec_16},
     |(_interruptNO_T_3[14:7]),
     |(_interruptNO_T_5[6:3]),
     |(_interruptNO_T_7[2:1]),
     _interruptNO_T_7[2] | _interruptNO_T_7[0]};
  assign io_out_entryPrivState_PRVM = {~(handleTrapUnderVS | handleTrapUnderHS), 1'h1};
  assign io_out_entryPrivState_V = handleTrapUnderVS;
  assign io_out_causeNO_Interrupt = hasIR;
  assign io_out_causeNO_ExceptionCode =
    {57'h0,
     hasIR
       ? interruptNO
       : io_in_trapInfo_bits_singleStep | io_in_trapInfo_bits_triggerFire
           ? 6'h3
           : {1'h0,
              |{highestPrioEXVec_23,
                highestPrioEXVec_22,
                highestPrioEXVec_21,
                highestPrioEXVec_20},
              |{highestPrioEXVec_15,
                highestPrioEXVec_13,
                highestPrioEXVec_12,
                highestPrioEXVec_11,
                highestPrioEXVec_10,
                highestPrioEXVec_9,
                highestPrioEXVec_8},
              |{_GEN_5,
                _GEN_4,
                _GEN_6,
                highestPrioEXVec_12 | highestPrioEXVec_20 | highestPrioEXVec_4},
              |(_exceptionRegular_T_7[2:1]),
              _exceptionRegular_T_7[2] | _exceptionRegular_T_7[0]}};
  assign io_out_pcFromXtvec =
    {62'((handleTrapUnderVS
            ? io_in_vstvec_addr
            : handleTrapUnderHS ? io_in_stvec_addr : io_in_mtvec_addr)
         + {56'h0,
            (handleTrapUnderVS
               ? io_in_vstvec_mode
               : handleTrapUnderHS ? io_in_stvec_mode : io_in_mtvec_mode) == 2'h1 & hasIR
              ? interruptNO
              : 6'h0}),
     2'h0};
endmodule

