// Generated by CIRCT firtool-1.62.0
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

module VSegmentUnit(
  input          clock,
  input          reset,
  input          io_in_valid,
  input  [34:0]  io_in_bits_uop_fuType,
  input  [8:0]   io_in_bits_uop_fuOpType,
  input          io_in_bits_uop_vecWen,
  input          io_in_bits_uop_v0Wen,
  input          io_in_bits_uop_vpu_vma,
  input          io_in_bits_uop_vpu_vta,
  input  [1:0]   io_in_bits_uop_vpu_vsew,
  input  [2:0]   io_in_bits_uop_vpu_vlmul,
  input          io_in_bits_uop_vpu_vm,
  input  [7:0]   io_in_bits_uop_vpu_vstart,
  input  [6:0]   io_in_bits_uop_vpu_vuopIdx,
  input  [2:0]   io_in_bits_uop_vpu_nf,
  input  [1:0]   io_in_bits_uop_vpu_veew,
  input  [7:0]   io_in_bits_uop_pdest,
  input          io_in_bits_uop_robIdx_flag,
  input  [7:0]   io_in_bits_uop_robIdx_value,
  input          io_in_bits_uop_lqIdx_flag,
  input  [6:0]   io_in_bits_uop_lqIdx_value,
  input          io_in_bits_uop_sqIdx_flag,
  input  [5:0]   io_in_bits_uop_sqIdx_value,
  input  [127:0] io_in_bits_src_0,
  input  [127:0] io_in_bits_src_1,
  input  [127:0] io_in_bits_src_2,
  input  [127:0] io_in_bits_src_3,
  input  [127:0] io_in_bits_src_4,
  output         io_uopwriteback_valid,
  output         io_uopwriteback_bits_uop_exceptionVec_4,
  output         io_uopwriteback_bits_uop_exceptionVec_5,
  output         io_uopwriteback_bits_uop_exceptionVec_6,
  output         io_uopwriteback_bits_uop_exceptionVec_7,
  output         io_uopwriteback_bits_uop_exceptionVec_13,
  output         io_uopwriteback_bits_uop_exceptionVec_15,
  output [8:0]   io_uopwriteback_bits_uop_fuOpType,
  output         io_uopwriteback_bits_uop_vecWen,
  output         io_uopwriteback_bits_uop_v0Wen,
  output         io_uopwriteback_bits_uop_vpu_vma,
  output         io_uopwriteback_bits_uop_vpu_vta,
  output [1:0]   io_uopwriteback_bits_uop_vpu_vsew,
  output         io_uopwriteback_bits_uop_vpu_vm,
  output [127:0] io_uopwriteback_bits_uop_vpu_vmask,
  output [7:0]   io_uopwriteback_bits_uop_vpu_vl,
  output [1:0]   io_uopwriteback_bits_uop_vpu_veew,
  output [7:0]   io_uopwriteback_bits_uop_pdest,
  output         io_uopwriteback_bits_uop_robIdx_flag,
  output [7:0]   io_uopwriteback_bits_uop_robIdx_value,
  output [127:0] io_uopwriteback_bits_data,
  output [2:0]   io_uopwriteback_bits_vdIdxInField,
  input          io_rdcache_req_ready,
  output         io_rdcache_req_valid,
  output [40:0]  io_rdcache_req_bits_vaddr,
  input          io_rdcache_resp_valid,
  input  [127:0] io_rdcache_resp_bits_data_delayed,
  input          io_rdcache_resp_bits_miss,
  output [35:0]  io_rdcache_s1_paddr_dup_lsu,
  output [35:0]  io_rdcache_s1_paddr_dup_dcache,
  input          io_rdcache_s2_bank_conflict,
  input          io_sbuffer_ready,
  output         io_sbuffer_valid,
  output [40:0]  io_sbuffer_bits_vaddr,
  output [127:0] io_sbuffer_bits_data,
  output [15:0]  io_sbuffer_bits_mask,
  output [35:0]  io_sbuffer_bits_addr,
  output         io_sbuffer_bits_vecValid,
  output         io_dtlb_req_valid,
  output [40:0]  io_dtlb_req_bits_vaddr,
  output [2:0]   io_dtlb_req_bits_cmd,
  output         io_dtlb_req_bits_debug_robIdx_flag,
  output [7:0]   io_dtlb_req_bits_debug_robIdx_value,
  input          io_dtlb_resp_valid,
  input  [35:0]  io_dtlb_resp_bits_paddr_0,
  input          io_dtlb_resp_bits_miss,
  input          io_dtlb_resp_bits_excp_0_pf_ld,
  input          io_dtlb_resp_bits_excp_0_pf_st,
  input          io_dtlb_resp_bits_excp_0_af_ld,
  input          io_dtlb_resp_bits_excp_0_af_st,
  input          io_pmpResp_ld,
  input          io_pmpResp_st,
  input          io_pmpResp_mmio,
  output         io_flush_sbuffer_valid,
  input          io_flush_sbuffer_empty,
  output         io_feedback_valid,
  output         io_feedback_bits_sqIdx_flag,
  output [5:0]   io_feedback_bits_sqIdx_value,
  output         io_feedback_bits_lqIdx_flag,
  output [6:0]   io_feedback_bits_lqIdx_value,
  output         io_exceptionInfo_valid,
  output [40:0]  io_exceptionInfo_bits_vaddr
);

  reg  [40:0]       instMicroOp_baseVaddr;
  reg               instMicroOp_uop_exceptionVec_4;
  reg               instMicroOp_uop_exceptionVec_5;
  reg               instMicroOp_uop_exceptionVec_6;
  reg               instMicroOp_uop_exceptionVec_7;
  reg               instMicroOp_uop_exceptionVec_13;
  reg               instMicroOp_uop_exceptionVec_15;
  reg  [34:0]       instMicroOp_uop_fuType;
  reg  [8:0]        instMicroOp_uop_fuOpType;
  reg               instMicroOp_uop_vpu_vma;
  reg               instMicroOp_uop_vpu_vta;
  reg  [1:0]        instMicroOp_uop_vpu_vsew;
  reg  [2:0]        instMicroOp_uop_vpu_vlmul;
  reg               instMicroOp_uop_vpu_vm;
  reg  [7:0]        instMicroOp_uop_vpu_vstart;
  reg  [2:0]        instMicroOp_uop_vpu_nf;
  reg  [1:0]        instMicroOp_uop_vpu_veew;
  reg               instMicroOp_uop_robIdx_flag;
  reg  [7:0]        instMicroOp_uop_robIdx_value;
  reg  [35:0]       instMicroOp_paddr;
  reg  [127:0]      instMicroOp_mask;
  reg  [2:0]        instMicroOp_alignedType;
  reg  [7:0]        instMicroOp_vl;
  reg  [7:0]        instMicroOp_uopFlowNumMask;
  reg  [40:0]       instMicroOp_exceptionVaddr;
  reg               instMicroOp_isFof;
  reg               instMicroOpValid;
  reg  [127:0]      data_0;
  reg  [127:0]      data_1;
  reg  [127:0]      data_2;
  reg  [127:0]      data_3;
  reg  [127:0]      data_4;
  reg  [127:0]      data_5;
  reg  [127:0]      data_6;
  reg  [127:0]      data_7;
  reg               uopq_0_uop_vecWen;
  reg               uopq_0_uop_v0Wen;
  reg  [6:0]        uopq_0_uop_vpu_vuopIdx;
  reg  [7:0]        uopq_0_uop_pdest;
  reg               uopq_0_uop_lqIdx_flag;
  reg  [6:0]        uopq_0_uop_lqIdx_value;
  reg               uopq_0_uop_sqIdx_flag;
  reg  [5:0]        uopq_0_uop_sqIdx_value;
  reg               uopq_1_uop_vecWen;
  reg               uopq_1_uop_v0Wen;
  reg  [6:0]        uopq_1_uop_vpu_vuopIdx;
  reg  [7:0]        uopq_1_uop_pdest;
  reg               uopq_1_uop_lqIdx_flag;
  reg  [6:0]        uopq_1_uop_lqIdx_value;
  reg               uopq_1_uop_sqIdx_flag;
  reg  [5:0]        uopq_1_uop_sqIdx_value;
  reg               uopq_2_uop_vecWen;
  reg               uopq_2_uop_v0Wen;
  reg  [6:0]        uopq_2_uop_vpu_vuopIdx;
  reg  [7:0]        uopq_2_uop_pdest;
  reg               uopq_2_uop_lqIdx_flag;
  reg  [6:0]        uopq_2_uop_lqIdx_value;
  reg               uopq_2_uop_sqIdx_flag;
  reg  [5:0]        uopq_2_uop_sqIdx_value;
  reg               uopq_3_uop_vecWen;
  reg               uopq_3_uop_v0Wen;
  reg  [6:0]        uopq_3_uop_vpu_vuopIdx;
  reg  [7:0]        uopq_3_uop_pdest;
  reg               uopq_3_uop_lqIdx_flag;
  reg  [6:0]        uopq_3_uop_lqIdx_value;
  reg               uopq_3_uop_sqIdx_flag;
  reg  [5:0]        uopq_3_uop_sqIdx_value;
  reg               uopq_4_uop_vecWen;
  reg               uopq_4_uop_v0Wen;
  reg  [6:0]        uopq_4_uop_vpu_vuopIdx;
  reg  [7:0]        uopq_4_uop_pdest;
  reg               uopq_4_uop_lqIdx_flag;
  reg  [6:0]        uopq_4_uop_lqIdx_value;
  reg               uopq_4_uop_sqIdx_flag;
  reg  [5:0]        uopq_4_uop_sqIdx_value;
  reg               uopq_5_uop_vecWen;
  reg               uopq_5_uop_v0Wen;
  reg  [6:0]        uopq_5_uop_vpu_vuopIdx;
  reg  [7:0]        uopq_5_uop_pdest;
  reg               uopq_5_uop_lqIdx_flag;
  reg  [6:0]        uopq_5_uop_lqIdx_value;
  reg               uopq_5_uop_sqIdx_flag;
  reg  [5:0]        uopq_5_uop_sqIdx_value;
  reg               uopq_6_uop_vecWen;
  reg               uopq_6_uop_v0Wen;
  reg  [6:0]        uopq_6_uop_vpu_vuopIdx;
  reg  [7:0]        uopq_6_uop_pdest;
  reg               uopq_6_uop_lqIdx_flag;
  reg  [6:0]        uopq_6_uop_lqIdx_value;
  reg               uopq_6_uop_sqIdx_flag;
  reg  [5:0]        uopq_6_uop_sqIdx_value;
  reg               uopq_7_uop_vecWen;
  reg               uopq_7_uop_v0Wen;
  reg  [6:0]        uopq_7_uop_vpu_vuopIdx;
  reg  [7:0]        uopq_7_uop_pdest;
  reg               uopq_7_uop_lqIdx_flag;
  reg  [6:0]        uopq_7_uop_lqIdx_value;
  reg               uopq_7_uop_sqIdx_flag;
  reg  [5:0]        uopq_7_uop_sqIdx_value;
  reg  [127:0]      stride_0;
  reg  [127:0]      stride_1;
  reg  [127:0]      stride_2;
  reg  [127:0]      stride_3;
  reg  [127:0]      stride_4;
  reg  [127:0]      stride_5;
  reg  [127:0]      stride_6;
  reg  [127:0]      stride_7;
  reg               enqPtr_flag;
  reg  [2:0]        enqPtr_value;
  reg               deqPtr_flag;
  reg  [2:0]        deqPtr_value;
  reg  [7:0]        segmentIdx;
  reg  [3:0]        fieldIdx;
  reg  [40:0]       segmentOffset;
  reg               splitPtr_flag;
  reg  [2:0]        splitPtr_value;
  reg  [40:0]       latchVaddr;
  wire [2:0]        _GEN = {1'h0, instMicroOp_uop_vpu_veew};
  wire [2:0]        _GEN_0 = {1'h0, instMicroOp_uop_vpu_vsew};
  wire [2:0]        issueEmul = 3'(3'(_GEN - _GEN_0) + instMicroOp_uop_vpu_vlmul);
  wire [2:0]        _issueUopFlowNumLog2_sewRealFlowLog2_T_3 =
    3'(3'(($signed(instMicroOp_uop_vpu_vlmul) > -3'sh1 ? 3'h0 : instMicroOp_uop_vpu_vlmul)
          - 3'h4) - _GEN_0);
  wire [2:0]        issueUopFlowNumLog2 =
    (instMicroOp_uop_fuOpType[6:5] == 2'h0 | instMicroOp_uop_fuOpType[6:5] == 2'h2
       ? 3'(3'(($signed(issueEmul) > -3'sh1 ? 3'h0 : issueEmul) - 3'h4) - _GEN)
       : 3'h0)
    | (instMicroOp_uop_fuOpType[6:5] == 2'h1
         ? _issueUopFlowNumLog2_sewRealFlowLog2_T_3
         : 3'h0)
    | ((&(instMicroOp_uop_fuOpType[6:5]))
         ? _issueUopFlowNumLog2_sewRealFlowLog2_T_3
         : 3'h0);
  wire [7:0]        issueIndexIdx =
    segmentIdx
    & 8'((8'h1 << 3'(3'(($signed(issueEmul) > 3'sh0 ? 3'h0 : issueEmul) - 3'h4) - _GEN))
         - 8'h1);
  wire [255:0]      _segmentActive_T = 256'h1 << segmentIdx;
  wire              segmentActive = |(_segmentActive_T[127:0] & instMicroOp_mask);
  reg  [3:0]        state;
  wire              _GEN_1 = state == 4'h5;
  wire [3:0]        _GEN_2 = {1'h0, instMicroOp_uop_vpu_nf};
  wire [2:0]        _emul_T_3 =
    3'(3'({1'h0, io_in_bits_uop_vpu_veew} - {1'h0, io_in_bits_uop_vpu_vsew})
       + io_in_bits_uop_vpu_vlmul);
  wire              _GEN_3 = io_in_valid & ~instMicroOpValid;
  wire [7:0][127:0] _GEN_4 =
    {{stride_7},
     {stride_6},
     {stride_5},
     {stride_4},
     {stride_3},
     {stride_2},
     {stride_1},
     {stride_0}};
  wire [2:0]        stridePtr_value;
  wire              _indexStride_T_111 = issueIndexIdx == 8'h0;
  wire              _indexStride_T_112 = issueIndexIdx == 8'h1;
  wire              _indexStride_T_100 = issueIndexIdx == 8'h2;
  wire              _indexStride_T_101 = issueIndexIdx == 8'h3;
  wire              _indexStride_T_75 = issueIndexIdx == 8'h4;
  wire              _indexStride_T_76 = issueIndexIdx == 8'h5;
  wire              _indexStride_T_77 = issueIndexIdx == 8'h6;
  wire              _indexStride_T_78 = issueIndexIdx == 8'h7;
  wire [40:0]       _vaddr_T_3 =
    41'(instMicroOp_baseVaddr
        + 41'({30'h0, {7'h0, fieldIdx} << instMicroOp_alignedType}
              + (instMicroOp_uop_fuOpType[5]
                   ? {9'h0,
                      {16'h0,
                       {8'h0,
                        instMicroOp_uop_vpu_veew == 2'h0
                          ? (_indexStride_T_111 ? _GEN_4[stridePtr_value][7:0] : 8'h0)
                            | (_indexStride_T_112 ? _GEN_4[stridePtr_value][15:8] : 8'h0)
                            | (_indexStride_T_100 ? _GEN_4[stridePtr_value][23:16] : 8'h0)
                            | (_indexStride_T_101 ? _GEN_4[stridePtr_value][31:24] : 8'h0)
                            | (_indexStride_T_75 ? _GEN_4[stridePtr_value][39:32] : 8'h0)
                            | (_indexStride_T_76 ? _GEN_4[stridePtr_value][47:40] : 8'h0)
                            | (_indexStride_T_77 ? _GEN_4[stridePtr_value][55:48] : 8'h0)
                            | (_indexStride_T_78 ? _GEN_4[stridePtr_value][63:56] : 8'h0)
                            | (issueIndexIdx == 8'h8
                                 ? _GEN_4[stridePtr_value][71:64]
                                 : 8'h0)
                            | (issueIndexIdx == 8'h9
                                 ? _GEN_4[stridePtr_value][79:72]
                                 : 8'h0)
                            | (issueIndexIdx == 8'hA
                                 ? _GEN_4[stridePtr_value][87:80]
                                 : 8'h0)
                            | (issueIndexIdx == 8'hB
                                 ? _GEN_4[stridePtr_value][95:88]
                                 : 8'h0)
                            | (issueIndexIdx == 8'hC
                                 ? _GEN_4[stridePtr_value][103:96]
                                 : 8'h0)
                            | (issueIndexIdx == 8'hD
                                 ? _GEN_4[stridePtr_value][111:104]
                                 : 8'h0)
                            | (issueIndexIdx == 8'hE
                                 ? _GEN_4[stridePtr_value][119:112]
                                 : 8'h0)
                            | (issueIndexIdx == 8'hF
                                 ? _GEN_4[stridePtr_value][127:120]
                                 : 8'h0)
                          : 8'h0}
                         | (instMicroOp_uop_vpu_veew == 2'h1
                              ? (_indexStride_T_111
                                   ? _GEN_4[stridePtr_value][15:0]
                                   : 16'h0)
                                | (_indexStride_T_112
                                     ? _GEN_4[stridePtr_value][31:16]
                                     : 16'h0)
                                | (_indexStride_T_100
                                     ? _GEN_4[stridePtr_value][47:32]
                                     : 16'h0)
                                | (_indexStride_T_101
                                     ? _GEN_4[stridePtr_value][63:48]
                                     : 16'h0)
                                | (_indexStride_T_75
                                     ? _GEN_4[stridePtr_value][79:64]
                                     : 16'h0)
                                | (_indexStride_T_76
                                     ? _GEN_4[stridePtr_value][95:80]
                                     : 16'h0)
                                | (_indexStride_T_77
                                     ? _GEN_4[stridePtr_value][111:96]
                                     : 16'h0)
                                | (_indexStride_T_78
                                     ? _GEN_4[stridePtr_value][127:112]
                                     : 16'h0)
                              : 16'h0)}
                        | (instMicroOp_uop_vpu_veew == 2'h2
                             ? (_indexStride_T_111
                                  ? _GEN_4[stridePtr_value][31:0]
                                  : 32'h0)
                               | (_indexStride_T_112
                                    ? _GEN_4[stridePtr_value][63:32]
                                    : 32'h0)
                               | (_indexStride_T_100
                                    ? _GEN_4[stridePtr_value][95:64]
                                    : 32'h0)
                               | (_indexStride_T_101
                                    ? _GEN_4[stridePtr_value][127:96]
                                    : 32'h0)
                             : 32'h0)}
                     | ((&instMicroOp_uop_vpu_veew)
                          ? (_indexStride_T_111 ? _GEN_4[stridePtr_value][40:0] : 41'h0)
                            | (_indexStride_T_112
                                 ? _GEN_4[stridePtr_value][104:64]
                                 : 41'h0)
                          : 41'h0)
                   : segmentOffset)));
  wire              _io_dtlb_req_valid_T = state == 4'h3;
  wire              canTriggerException = segmentIdx == 8'h0 | ~instMicroOp_isFof;
  wire [1:0]        _addr_aligned_T_4 =
    instMicroOp_uop_fuOpType[5] ? instMicroOp_uop_vpu_vsew : instMicroOp_uop_vpu_veew;
  wire              addr_aligned =
    _addr_aligned_T_4 == 2'h0 | _addr_aligned_T_4 == 2'h1 & ~(_vaddr_T_3[0])
    | _addr_aligned_T_4 == 2'h2 & _vaddr_T_3[1:0] == 2'h0 | (&_addr_aligned_T_4)
    & _vaddr_T_3[2:0] == 3'h0;
  wire              exception_va =
    _GEN_1
    & (instMicroOp_uop_exceptionVec_15 | instMicroOp_uop_exceptionVec_13
       | instMicroOp_uop_exceptionVec_7 | instMicroOp_uop_exceptionVec_5 | ~addr_aligned
       & canTriggerException);
  wire              exception_pa =
    _GEN_1 & (io_pmpResp_st | io_pmpResp_ld | io_pmpResp_mmio) & canTriggerException;
  wire [3:0]        _splitData_T = segmentIdx[3:0] & instMicroOp_uopFlowNumMask[3:0];
  wire [7:0][127:0] _GEN_5 =
    {{data_7}, {data_6}, {data_5}, {data_4}, {data_3}, {data_2}, {data_1}, {data_0}};
  wire [127:0]      _GEN_6 = _GEN_5[splitPtr_value];
  wire [2:0]        _splitData_T_65 = segmentIdx[2:0] & instMicroOp_uopFlowNumMask[2:0];
  wire [1:0]        _splitData_T_98 = segmentIdx[1:0] & instMicroOp_uopFlowNumMask[1:0];
  wire              _splitData_T_119 = segmentIdx[0] & instMicroOp_uopFlowNumMask[0];
  wire              _segmentInactiveFinish_T = state == 4'h8;
  wire              _GEN_7 = _segmentInactiveFinish_T & segmentActive;
  wire              _flowData_T_15 = instMicroOp_alignedType == 3'h0;
  wire              _flowData_T_16 = instMicroOp_alignedType == 3'h1;
  wire              _flowData_T_17 = instMicroOp_alignedType == 3'h2;
  wire              _flowData_T_18 = instMicroOp_alignedType == 3'h3;
  wire              _flowData_T_19 = instMicroOp_alignedType == 3'h4;
  wire [127:0]      splitData =
    (_flowData_T_15
       ? {120'h0,
          (_splitData_T == 4'h0 ? _GEN_6[7:0] : 8'h0)
            | (_splitData_T == 4'h1 ? _GEN_6[15:8] : 8'h0)
            | (_splitData_T == 4'h2 ? _GEN_6[23:16] : 8'h0)
            | (_splitData_T == 4'h3 ? _GEN_6[31:24] : 8'h0)
            | (_splitData_T == 4'h4 ? _GEN_6[39:32] : 8'h0)
            | (_splitData_T == 4'h5 ? _GEN_6[47:40] : 8'h0)
            | (_splitData_T == 4'h6 ? _GEN_6[55:48] : 8'h0)
            | (_splitData_T == 4'h7 ? _GEN_6[63:56] : 8'h0)
            | (_splitData_T == 4'h8 ? _GEN_6[71:64] : 8'h0)
            | (_splitData_T == 4'h9 ? _GEN_6[79:72] : 8'h0)
            | (_splitData_T == 4'hA ? _GEN_6[87:80] : 8'h0)
            | (_splitData_T == 4'hB ? _GEN_6[95:88] : 8'h0)
            | (_splitData_T == 4'hC ? _GEN_6[103:96] : 8'h0)
            | (_splitData_T == 4'hD ? _GEN_6[111:104] : 8'h0)
            | (_splitData_T == 4'hE ? _GEN_6[119:112] : 8'h0)
            | ((&_splitData_T) ? _GEN_6[127:120] : 8'h0)}
       : 128'h0)
    | (_flowData_T_16
         ? {112'h0,
            (_splitData_T_65 == 3'h0 ? _GEN_6[15:0] : 16'h0)
              | (_splitData_T_65 == 3'h1 ? _GEN_6[31:16] : 16'h0)
              | (_splitData_T_65 == 3'h2 ? _GEN_6[47:32] : 16'h0)
              | (_splitData_T_65 == 3'h3 ? _GEN_6[63:48] : 16'h0)
              | (_splitData_T_65 == 3'h4 ? _GEN_6[79:64] : 16'h0)
              | (_splitData_T_65 == 3'h5 ? _GEN_6[95:80] : 16'h0)
              | (_splitData_T_65 == 3'h6 ? _GEN_6[111:96] : 16'h0)
              | ((&_splitData_T_65) ? _GEN_6[127:112] : 16'h0)}
         : 128'h0)
    | (_flowData_T_17
         ? {96'h0,
            (_splitData_T_98 == 2'h0 ? _GEN_6[31:0] : 32'h0)
              | (_splitData_T_98 == 2'h1 ? _GEN_6[63:32] : 32'h0)
              | (_splitData_T_98 == 2'h2 ? _GEN_6[95:64] : 32'h0)
              | ((&_splitData_T_98) ? _GEN_6[127:96] : 32'h0)}
         : 128'h0)
    | (_flowData_T_18
         ? {64'h0,
            (_splitData_T_119 ? 64'h0 : _GEN_6[63:0])
              | (_splitData_T_119 ? _GEN_6[127:64] : 64'h0)}
         : 128'h0) | (_flowData_T_19 ? _GEN_6 : 128'h0);
  wire [22:0]       _wmask_T_13 =
    {15'h0,
     {4'h0,
      {2'h0,
       {1'h0, ~(|(instMicroOp_alignedType[1:0]))}
         | {2{instMicroOp_alignedType[1:0] == 2'h1}}}
        | {4{instMicroOp_alignedType[1:0] == 2'h2}}}
       | {8{&(instMicroOp_alignedType[1:0])}}} << latchVaddr[3:0];
  wire              io_rdcache_req_valid_0 =
    state == 4'h6 & (instMicroOp_uop_fuType[31] | instMicroOp_uop_fuType[33]);
  wire              _segmentInactiveFinish_T_1 = state == 4'h9;
  wire              io_sbuffer_valid_0 = _segmentInactiveFinish_T_1 & segmentActive;
  wire [7:0]        _GEN_8 =
    {{uopq_7_uop_vecWen},
     {uopq_6_uop_vecWen},
     {uopq_5_uop_vecWen},
     {uopq_4_uop_vecWen},
     {uopq_3_uop_vecWen},
     {uopq_2_uop_vecWen},
     {uopq_1_uop_vecWen},
     {uopq_0_uop_vecWen}};
  wire [7:0]        _GEN_9 =
    {{uopq_7_uop_v0Wen},
     {uopq_6_uop_v0Wen},
     {uopq_5_uop_v0Wen},
     {uopq_4_uop_v0Wen},
     {uopq_3_uop_v0Wen},
     {uopq_2_uop_v0Wen},
     {uopq_1_uop_v0Wen},
     {uopq_0_uop_v0Wen}};
  wire [7:0][6:0]   _GEN_10 =
    {{uopq_7_uop_vpu_vuopIdx},
     {uopq_6_uop_vpu_vuopIdx},
     {uopq_5_uop_vpu_vuopIdx},
     {uopq_4_uop_vpu_vuopIdx},
     {uopq_3_uop_vpu_vuopIdx},
     {uopq_2_uop_vpu_vuopIdx},
     {uopq_1_uop_vpu_vuopIdx},
     {uopq_0_uop_vpu_vuopIdx}};
  wire [6:0]        _GEN_11 = _GEN_10[deqPtr_value];
  wire [7:0][7:0]   _GEN_12 =
    {{uopq_7_uop_pdest},
     {uopq_6_uop_pdest},
     {uopq_5_uop_pdest},
     {uopq_4_uop_pdest},
     {uopq_3_uop_pdest},
     {uopq_2_uop_pdest},
     {uopq_1_uop_pdest},
     {uopq_0_uop_pdest}};
  wire [7:0]        _GEN_13 =
    {{uopq_7_uop_lqIdx_flag},
     {uopq_6_uop_lqIdx_flag},
     {uopq_5_uop_lqIdx_flag},
     {uopq_4_uop_lqIdx_flag},
     {uopq_3_uop_lqIdx_flag},
     {uopq_2_uop_lqIdx_flag},
     {uopq_1_uop_lqIdx_flag},
     {uopq_0_uop_lqIdx_flag}};
  wire [7:0][6:0]   _GEN_14 =
    {{uopq_7_uop_lqIdx_value},
     {uopq_6_uop_lqIdx_value},
     {uopq_5_uop_lqIdx_value},
     {uopq_4_uop_lqIdx_value},
     {uopq_3_uop_lqIdx_value},
     {uopq_2_uop_lqIdx_value},
     {uopq_1_uop_lqIdx_value},
     {uopq_0_uop_lqIdx_value}};
  wire [7:0]        _GEN_15 =
    {{uopq_7_uop_sqIdx_flag},
     {uopq_6_uop_sqIdx_flag},
     {uopq_5_uop_sqIdx_flag},
     {uopq_4_uop_sqIdx_flag},
     {uopq_3_uop_sqIdx_flag},
     {uopq_2_uop_sqIdx_flag},
     {uopq_1_uop_sqIdx_flag},
     {uopq_0_uop_sqIdx_flag}};
  wire [7:0][5:0]   _GEN_16 =
    {{uopq_7_uop_sqIdx_value},
     {uopq_6_uop_sqIdx_value},
     {uopq_5_uop_sqIdx_value},
     {uopq_4_uop_sqIdx_value},
     {uopq_3_uop_sqIdx_value},
     {uopq_2_uop_sqIdx_value},
     {uopq_1_uop_sqIdx_value},
     {uopq_0_uop_sqIdx_value}};
  wire [7:0]        _splitPtrOffset_T_4 = 8'h1 << io_in_bits_uop_vpu_vlmul;
  wire [7:0]        _splitPtrOffset_T_8 = 8'h1 << _emul_T_3;
  wire              _fieldIdx_T = fieldIdx == _GEN_2;
  wire              _splitPtrNext_T_2 = _fieldIdx_T | ~segmentActive;
  wire [8:0]        _segmentIdx_T_2 = 9'({1'h0, segmentIdx} + 9'h1);
  wire [8:0]        _splitPtrNext_T_4 = _segmentIdx_T_2 >> issueUopFlowNumLog2;
  wire [3:0]        _io_exceptionInfo_valid_T_5 = {deqPtr_flag, deqPtr_value};
  wire [3:0]        _GEN_17 = {deqPtr_flag, deqPtr_value};
  wire [3:0]        _splitPtrNext_new_ptr_T_1 = 4'(_GEN_17 + _splitPtrNext_T_4[3:0]);
  wire [3:0]        _splitPtrNext_new_ptr_T_6 =
    4'({splitPtr_flag, splitPtr_value}
       + (io_in_bits_uop_fuOpType[5]
            ? ($signed(io_in_bits_uop_vpu_vlmul) < 3'sh0
                 ? 4'h1
                 : _splitPtrOffset_T_4[3:0])
            : $signed(_emul_T_3) < 3'sh0 ? 4'h1 : _splitPtrOffset_T_8[3:0]));
  wire              splitPtrNext_flag =
    _splitPtrNext_T_2 ? _splitPtrNext_new_ptr_T_1[3] : _splitPtrNext_new_ptr_T_6[3];
  wire [2:0]        splitPtrNext_value =
    _splitPtrNext_T_2 ? _splitPtrNext_new_ptr_T_1[2:0] : _splitPtrNext_new_ptr_T_6[2:0];
  wire [7:0]        _strideOffset_T_2 =
    segmentIdx >> 3'(3'(($signed(issueEmul) > 3'sh0 ? 3'h0 : issueEmul) - 3'h4) - _GEN);
  wire [3:0]        _stridePtr_new_ptr_T_1 =
    4'(_GEN_17 + (instMicroOp_uop_fuOpType[5] ? _strideOffset_T_2[3:0] : 4'h0));
  assign stridePtr_value = _stridePtr_new_ptr_T_1[2:0];
  wire              stridePtr_flag = _stridePtr_new_ptr_T_1[3];
  wire [2:0]        _vdIdxInField_T_2 =
    io_in_bits_uop_fuOpType[5] ? instMicroOp_uop_vpu_vlmul : issueEmul;
  wire [2:0]        vdIdxInField =
    {1'h0,
     {1'h0, _vdIdxInField_T_2 == 3'h1 & _GEN_11[0]}
       | (_vdIdxInField_T_2 == 3'h2 ? _GEN_11[1:0] : 2'h0)}
    | (_vdIdxInField_T_2 == 3'h3 ? _GEN_11[2:0] : 3'h0);
  wire [1:0]        realEw =
    instMicroOp_uop_fuOpType[5] ? instMicroOp_uop_vpu_vsew : instMicroOp_uop_vpu_veew;
  wire              _maskDataVec_maskDataVec_7_T = realEw == 2'h0;
  wire              _maskDataVec_maskDataVec_7_T_2 = realEw == 2'h1;
  wire              _maskDataVec_maskDataVec_7_T_4 = realEw == 2'h2;
  wire [15:0]       _maskDataVec_maskDataVec_0_T_8 =
    _maskDataVec_maskDataVec_7_T ? instMicroOp_mask[15:0] : 16'h0;
  wire [7:0]        _GEN_18 =
    _maskDataVec_maskDataVec_0_T_8[7:0]
    | (_maskDataVec_maskDataVec_7_T_2 ? instMicroOp_mask[7:0] : 8'h0);
  wire [3:0]        _GEN_19 =
    _GEN_18[3:0] | (_maskDataVec_maskDataVec_7_T_4 ? instMicroOp_mask[3:0] : 4'h0);
  wire [15:0]       _maskDataVec_maskDataVec_1_T_8 =
    _maskDataVec_maskDataVec_7_T ? instMicroOp_mask[31:16] : 16'h0;
  wire [7:0]        _GEN_20 =
    _maskDataVec_maskDataVec_1_T_8[7:0]
    | (_maskDataVec_maskDataVec_7_T_2 ? instMicroOp_mask[15:8] : 8'h0);
  wire [3:0]        _GEN_21 =
    _GEN_20[3:0] | (_maskDataVec_maskDataVec_7_T_4 ? instMicroOp_mask[7:4] : 4'h0);
  wire [15:0]       _maskDataVec_maskDataVec_2_T_8 =
    _maskDataVec_maskDataVec_7_T ? instMicroOp_mask[47:32] : 16'h0;
  wire [7:0]        _GEN_22 =
    _maskDataVec_maskDataVec_2_T_8[7:0]
    | (_maskDataVec_maskDataVec_7_T_2 ? instMicroOp_mask[23:16] : 8'h0);
  wire [3:0]        _GEN_23 =
    _GEN_22[3:0] | (_maskDataVec_maskDataVec_7_T_4 ? instMicroOp_mask[11:8] : 4'h0);
  wire [15:0]       _maskDataVec_maskDataVec_3_T_8 =
    _maskDataVec_maskDataVec_7_T ? instMicroOp_mask[63:48] : 16'h0;
  wire [7:0]        _GEN_24 =
    _maskDataVec_maskDataVec_3_T_8[7:0]
    | (_maskDataVec_maskDataVec_7_T_2 ? instMicroOp_mask[31:24] : 8'h0);
  wire [3:0]        _GEN_25 =
    _GEN_24[3:0] | (_maskDataVec_maskDataVec_7_T_4 ? instMicroOp_mask[15:12] : 4'h0);
  wire [15:0]       _maskDataVec_maskDataVec_4_T_8 =
    _maskDataVec_maskDataVec_7_T ? instMicroOp_mask[79:64] : 16'h0;
  wire [7:0]        _GEN_26 =
    _maskDataVec_maskDataVec_4_T_8[7:0]
    | (_maskDataVec_maskDataVec_7_T_2 ? instMicroOp_mask[39:32] : 8'h0);
  wire [3:0]        _GEN_27 =
    _GEN_26[3:0] | (_maskDataVec_maskDataVec_7_T_4 ? instMicroOp_mask[19:16] : 4'h0);
  wire [15:0]       _maskDataVec_maskDataVec_5_T_8 =
    _maskDataVec_maskDataVec_7_T ? instMicroOp_mask[95:80] : 16'h0;
  wire [7:0]        _GEN_28 =
    _maskDataVec_maskDataVec_5_T_8[7:0]
    | (_maskDataVec_maskDataVec_7_T_2 ? instMicroOp_mask[47:40] : 8'h0);
  wire [3:0]        _GEN_29 =
    _GEN_28[3:0] | (_maskDataVec_maskDataVec_7_T_4 ? instMicroOp_mask[23:20] : 4'h0);
  wire [15:0]       _maskDataVec_maskDataVec_6_T_8 =
    _maskDataVec_maskDataVec_7_T ? instMicroOp_mask[111:96] : 16'h0;
  wire [7:0]        _GEN_30 =
    _maskDataVec_maskDataVec_6_T_8[7:0]
    | (_maskDataVec_maskDataVec_7_T_2 ? instMicroOp_mask[55:48] : 8'h0);
  wire [3:0]        _GEN_31 =
    _GEN_30[3:0] | (_maskDataVec_maskDataVec_7_T_4 ? instMicroOp_mask[27:24] : 4'h0);
  wire [15:0]       _maskDataVec_maskDataVec_7_T_8 =
    _maskDataVec_maskDataVec_7_T ? instMicroOp_mask[127:112] : 16'h0;
  wire [7:0]        _GEN_32 =
    _maskDataVec_maskDataVec_7_T_8[7:0]
    | (_maskDataVec_maskDataVec_7_T_2 ? instMicroOp_mask[63:56] : 8'h0);
  wire [3:0]        _GEN_33 =
    _GEN_32[3:0] | (_maskDataVec_maskDataVec_7_T_4 ? instMicroOp_mask[31:28] : 4'h0);
  wire              _io_exceptionInfo_valid_T = state == 4'hA;
  wire [3:0]        _io_exceptionInfo_valid_T_4 = {enqPtr_flag, enqPtr_value};
  wire              io_uopwriteback_valid_0 =
    _io_exceptionInfo_valid_T
    & _io_exceptionInfo_valid_T_4 != _io_exceptionInfo_valid_T_5;
  wire [7:0][15:0]  _GEN_34 =
    {{{_maskDataVec_maskDataVec_7_T_8[15:8],
       _GEN_32[7:4],
       _GEN_33[3:2],
       _GEN_33[1:0] | ((&realEw) ? instMicroOp_mask[15:14] : 2'h0)}},
     {{_maskDataVec_maskDataVec_6_T_8[15:8],
       _GEN_30[7:4],
       _GEN_31[3:2],
       _GEN_31[1:0] | ((&realEw) ? instMicroOp_mask[13:12] : 2'h0)}},
     {{_maskDataVec_maskDataVec_5_T_8[15:8],
       _GEN_28[7:4],
       _GEN_29[3:2],
       _GEN_29[1:0] | ((&realEw) ? instMicroOp_mask[11:10] : 2'h0)}},
     {{_maskDataVec_maskDataVec_4_T_8[15:8],
       _GEN_26[7:4],
       _GEN_27[3:2],
       _GEN_27[1:0] | ((&realEw) ? instMicroOp_mask[9:8] : 2'h0)}},
     {{_maskDataVec_maskDataVec_3_T_8[15:8],
       _GEN_24[7:4],
       _GEN_25[3:2],
       _GEN_25[1:0] | ((&realEw) ? instMicroOp_mask[7:6] : 2'h0)}},
     {{_maskDataVec_maskDataVec_2_T_8[15:8],
       _GEN_22[7:4],
       _GEN_23[3:2],
       _GEN_23[1:0] | ((&realEw) ? instMicroOp_mask[5:4] : 2'h0)}},
     {{_maskDataVec_maskDataVec_1_T_8[15:8],
       _GEN_20[7:4],
       _GEN_21[3:2],
       _GEN_21[1:0] | ((&realEw) ? instMicroOp_mask[3:2] : 2'h0)}},
     {{_maskDataVec_maskDataVec_0_T_8[15:8],
       _GEN_18[7:4],
       _GEN_19[3:2],
       _GEN_19[1:0] | ((&realEw) ? instMicroOp_mask[1:0] : 2'h0)}}};
  wire [4:0]        uopFlowNum_segmentIndexFlowNum =
    {io_in_bits_uop_vpu_vlmul == 3'h0 | io_in_bits_uop_vpu_vlmul == 3'h1
       | io_in_bits_uop_vpu_vlmul == 3'h2 | io_in_bits_uop_vpu_vlmul == 3'h3,
     &io_in_bits_uop_vpu_vlmul,
     io_in_bits_uop_vpu_vlmul == 3'h6,
     io_in_bits_uop_vpu_vlmul == 3'h5,
     1'h0} >> io_in_bits_uop_vpu_vsew;
  wire              _uopFlowNum_T_157 = _emul_T_3 == 3'h5;
  wire              _uopFlowNum_T_158 = _emul_T_3 == 3'h6;
  wire [4:0]        _GEN_35 = {3'h0, io_in_bits_uop_vpu_veew};
  wire              _GEN_36 =
    _emul_T_3 == 3'h0 | _emul_T_3 == 3'h1 | _emul_T_3 == 3'h2 | _emul_T_3 == 3'h3;
  wire [255:0]      _srcMask_vlMask_T = 256'h1 << instMicroOp_vl;
  wire [255:0]      _srcMask_startMask_T = 256'h1 << instMicroOp_uop_vpu_vstart;
  wire              _GEN_37 = io_in_valid & enqPtr_value == 3'h0;
  wire              _GEN_38 = io_in_valid & enqPtr_value == 3'h1;
  wire              _GEN_39 = io_in_valid & enqPtr_value == 3'h2;
  wire              _GEN_40 = io_in_valid & enqPtr_value == 3'h3;
  wire              _GEN_41 = io_in_valid & enqPtr_value == 3'h4;
  wire              _GEN_42 = io_in_valid & enqPtr_value == 3'h5;
  wire              _GEN_43 = io_in_valid & enqPtr_value == 3'h6;
  wire              _GEN_44 = io_in_valid & (&enqPtr_value);
  wire              _GEN_45 = io_dtlb_resp_valid & state == 4'h4;
  wire [63:0]       _cacheData_T_33 =
    latchVaddr[3:0] == 4'h0 ? io_rdcache_resp_bits_data_delayed[63:0] : 64'h0;
  wire [55:0]       _GEN_46 =
    _cacheData_T_33[55:0]
    | (latchVaddr[3:0] == 4'h1 ? io_rdcache_resp_bits_data_delayed[63:8] : 56'h0);
  wire [47:0]       _GEN_47 =
    _GEN_46[47:0]
    | (latchVaddr[3:0] == 4'h2 ? io_rdcache_resp_bits_data_delayed[63:16] : 48'h0);
  wire [39:0]       _GEN_48 =
    _GEN_47[39:0]
    | (latchVaddr[3:0] == 4'h3 ? io_rdcache_resp_bits_data_delayed[63:24] : 40'h0);
  wire [31:0]       _GEN_49 =
    _GEN_48[31:0]
    | (latchVaddr[3:0] == 4'h4 ? io_rdcache_resp_bits_data_delayed[63:32] : 32'h0);
  wire [23:0]       _GEN_50 =
    _GEN_49[23:0]
    | (latchVaddr[3:0] == 4'h5 ? io_rdcache_resp_bits_data_delayed[63:40] : 24'h0);
  wire [15:0]       _GEN_51 =
    _GEN_50[15:0]
    | (latchVaddr[3:0] == 4'h6 ? io_rdcache_resp_bits_data_delayed[63:48] : 16'h0);
  wire [63:0]       _cacheData_T_56 =
    {_cacheData_T_33[63:56],
     _GEN_46[55:48],
     _GEN_47[47:40],
     _GEN_48[39:32],
     _GEN_49[31:24],
     _GEN_50[23:16],
     _GEN_51[15:8],
     _GEN_51[7:0]
       | (latchVaddr[3:0] == 4'h7 ? io_rdcache_resp_bits_data_delayed[63:56] : 8'h0)}
    | (latchVaddr[3:0] == 4'h8 ? io_rdcache_resp_bits_data_delayed[127:64] : 64'h0);
  wire [55:0]       _GEN_52 =
    _cacheData_T_56[55:0]
    | (latchVaddr[3:0] == 4'h9 ? io_rdcache_resp_bits_data_delayed[127:72] : 56'h0);
  wire [47:0]       _GEN_53 =
    _GEN_52[47:0]
    | (latchVaddr[3:0] == 4'hA ? io_rdcache_resp_bits_data_delayed[127:80] : 48'h0);
  wire [39:0]       _GEN_54 =
    _GEN_53[39:0]
    | (latchVaddr[3:0] == 4'hB ? io_rdcache_resp_bits_data_delayed[127:88] : 40'h0);
  wire [31:0]       _GEN_55 =
    _GEN_54[31:0]
    | (latchVaddr[3:0] == 4'hC ? io_rdcache_resp_bits_data_delayed[127:96] : 32'h0);
  wire [23:0]       _GEN_56 =
    _GEN_55[23:0]
    | (latchVaddr[3:0] == 4'hD ? io_rdcache_resp_bits_data_delayed[127:104] : 24'h0);
  wire [15:0]       _GEN_57 =
    _GEN_56[15:0]
    | (latchVaddr[3:0] == 4'hE ? io_rdcache_resp_bits_data_delayed[127:112] : 16'h0);
  wire [7:0]        _pickData_T_1 =
    _GEN_57[7:0]
    | ((&(latchVaddr[3:0])) ? io_rdcache_resp_bits_data_delayed[127:120] : 8'h0);
  wire [63:0]       pickData =
    ((|(instMicroOp_alignedType[1:0])) ? 64'h0 : {56'h0, _pickData_T_1})
    | (instMicroOp_alignedType[1:0] == 2'h1
         ? {48'h0, _GEN_57[15:8], _pickData_T_1}
         : 64'h0)
    | (instMicroOp_alignedType[1:0] == 2'h2
         ? {32'h0, _GEN_55[31:24], _GEN_56[23:16], _GEN_57[15:8], _pickData_T_1}
         : 64'h0)
    | ((&(instMicroOp_alignedType[1:0]))
         ? {_cacheData_T_56[63:56],
            _GEN_52[55:48],
            _GEN_53[47:40],
            _GEN_54[39:32],
            _GEN_55[31:24],
            _GEN_56[23:16],
            _GEN_57[15:8],
            _pickData_T_1}
         : 64'h0);
  wire [127:0]      mergedData =
    ((|(instMicroOp_alignedType[1:0]))
       ? 128'h0
       : {(&_splitData_T) ? pickData[7:0] : _GEN_6[127:120],
          _splitData_T == 4'hE ? pickData[7:0] : _GEN_6[119:112],
          _splitData_T == 4'hD ? pickData[7:0] : _GEN_6[111:104],
          _splitData_T == 4'hC ? pickData[7:0] : _GEN_6[103:96],
          _splitData_T == 4'hB ? pickData[7:0] : _GEN_6[95:88],
          _splitData_T == 4'hA ? pickData[7:0] : _GEN_6[87:80],
          _splitData_T == 4'h9 ? pickData[7:0] : _GEN_6[79:72],
          _splitData_T == 4'h8 ? pickData[7:0] : _GEN_6[71:64],
          _splitData_T == 4'h7 ? pickData[7:0] : _GEN_6[63:56],
          _splitData_T == 4'h6 ? pickData[7:0] : _GEN_6[55:48],
          _splitData_T == 4'h5 ? pickData[7:0] : _GEN_6[47:40],
          _splitData_T == 4'h4 ? pickData[7:0] : _GEN_6[39:32],
          _splitData_T == 4'h3 ? pickData[7:0] : _GEN_6[31:24],
          _splitData_T == 4'h2 ? pickData[7:0] : _GEN_6[23:16],
          _splitData_T == 4'h1 ? pickData[7:0] : _GEN_6[15:8],
          _splitData_T == 4'h0 ? pickData[7:0] : _GEN_6[7:0]})
    | (instMicroOp_alignedType[1:0] == 2'h1
         ? {(&_splitData_T_65) ? pickData[15:0] : _GEN_6[127:112],
            _splitData_T_65 == 3'h6 ? pickData[15:0] : _GEN_6[111:96],
            _splitData_T_65 == 3'h5 ? pickData[15:0] : _GEN_6[95:80],
            _splitData_T_65 == 3'h4 ? pickData[15:0] : _GEN_6[79:64],
            _splitData_T_65 == 3'h3 ? pickData[15:0] : _GEN_6[63:48],
            _splitData_T_65 == 3'h2 ? pickData[15:0] : _GEN_6[47:32],
            _splitData_T_65 == 3'h1 ? pickData[15:0] : _GEN_6[31:16],
            _splitData_T_65 == 3'h0 ? pickData[15:0] : _GEN_6[15:0]}
         : 128'h0)
    | (instMicroOp_alignedType[1:0] == 2'h2
         ? {(&_splitData_T_98) ? pickData[31:0] : _GEN_6[127:96],
            _splitData_T_98 == 2'h2 ? pickData[31:0] : _GEN_6[95:64],
            _splitData_T_98 == 2'h1 ? pickData[31:0] : _GEN_6[63:32],
            _splitData_T_98 == 2'h0 ? pickData[31:0] : _GEN_6[31:0]}
         : 128'h0)
    | ((&(instMicroOp_alignedType[1:0]))
         ? {_splitData_T_119 ? pickData : _GEN_6[127:64],
            _splitData_T_119 ? _GEN_6[63:0] : pickData}
         : 128'h0);
  always @(posedge clock) begin
    if (_GEN_3) begin
      instMicroOp_baseVaddr <= io_in_bits_src_0[40:0];
      instMicroOp_uop_fuType <= io_in_bits_uop_fuType;
      instMicroOp_uop_fuOpType <= io_in_bits_uop_fuOpType;
      instMicroOp_uop_vpu_vma <= io_in_bits_uop_vpu_vma;
      instMicroOp_uop_vpu_vta <= io_in_bits_uop_vpu_vta;
      instMicroOp_uop_vpu_vsew <= io_in_bits_uop_vpu_vsew;
      instMicroOp_uop_vpu_vlmul <= io_in_bits_uop_vpu_vlmul;
      instMicroOp_uop_vpu_vm <= io_in_bits_uop_vpu_vm;
      instMicroOp_uop_vpu_vstart <= io_in_bits_uop_vpu_vstart;
      instMicroOp_uop_vpu_nf <= io_in_bits_uop_vpu_nf;
      instMicroOp_uop_vpu_veew <= io_in_bits_uop_vpu_veew;
      instMicroOp_uop_robIdx_flag <= io_in_bits_uop_robIdx_flag;
      instMicroOp_uop_robIdx_value <= io_in_bits_uop_robIdx_value;
      instMicroOp_mask <=
        (instMicroOp_uop_vpu_vm
           ? 128'hFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
           : io_in_bits_src_3) & 128'(_srcMask_vlMask_T[127:0] - 128'h1)
        & ~(128'(_srcMask_startMask_T[127:0] - 128'h1));
      instMicroOp_alignedType <=
        {1'h0,
         io_in_bits_uop_fuOpType[5] ? io_in_bits_uop_vpu_vsew : io_in_bits_uop_vpu_veew};
      instMicroOp_vl <= io_in_bits_src_4[7:0];
      instMicroOp_uopFlowNumMask <=
        8'({3'h0,
            (io_in_bits_uop_fuOpType[6:5] == 2'h0
               ? {_GEN_36, &_emul_T_3, _uopFlowNum_T_158, _uopFlowNum_T_157, 1'h0}
                 >> _GEN_35
               : 5'h0)
              | (io_in_bits_uop_fuOpType[6:5] == 2'h2
                   ? {_GEN_36, &_emul_T_3, _uopFlowNum_T_158, _uopFlowNum_T_157, 1'h0}
                     >> _GEN_35
                   : 5'h0)
              | (io_in_bits_uop_fuOpType[6:5] == 2'h1
                   ? uopFlowNum_segmentIndexFlowNum
                   : 5'h0)
              | ((&(io_in_bits_uop_fuOpType[6:5]))
                   ? uopFlowNum_segmentIndexFlowNum
                   : 5'h0)} - 8'h1);
      instMicroOp_isFof <=
        io_in_bits_uop_fuOpType == 9'h90
        & (instMicroOp_uop_fuType[31] | instMicroOp_uop_fuType[33]);
    end
    if (_GEN_1) begin
      instMicroOp_uop_exceptionVec_4 <=
        ~addr_aligned & (instMicroOp_uop_fuType[31] | instMicroOp_uop_fuType[33])
        & canTriggerException;
      instMicroOp_uop_exceptionVec_5 <=
        (instMicroOp_uop_exceptionVec_5 | io_pmpResp_ld | io_pmpResp_mmio)
        & canTriggerException;
      instMicroOp_uop_exceptionVec_6 <=
        ~addr_aligned & ~(instMicroOp_uop_fuType[31] | instMicroOp_uop_fuType[33])
        & canTriggerException;
      instMicroOp_uop_exceptionVec_7 <=
        (instMicroOp_uop_exceptionVec_7 | io_pmpResp_st | io_pmpResp_mmio)
        & canTriggerException;
    end
    else begin
      instMicroOp_uop_exceptionVec_4 <= ~_GEN_3 & instMicroOp_uop_exceptionVec_4;
      if (_GEN_45) begin
        instMicroOp_uop_exceptionVec_5 <=
          io_dtlb_resp_bits_excp_0_af_ld & canTriggerException;
        instMicroOp_uop_exceptionVec_7 <=
          io_dtlb_resp_bits_excp_0_af_st & canTriggerException;
      end
      else begin
        instMicroOp_uop_exceptionVec_5 <= ~_GEN_3 & instMicroOp_uop_exceptionVec_5;
        instMicroOp_uop_exceptionVec_7 <= ~_GEN_3 & instMicroOp_uop_exceptionVec_7;
      end
      instMicroOp_uop_exceptionVec_6 <= ~_GEN_3 & instMicroOp_uop_exceptionVec_6;
    end
    if (_GEN_45) begin
      instMicroOp_uop_exceptionVec_13 <=
        io_dtlb_resp_bits_excp_0_pf_ld & canTriggerException;
      instMicroOp_uop_exceptionVec_15 <=
        io_dtlb_resp_bits_excp_0_pf_st & canTriggerException;
    end
    else begin
      instMicroOp_uop_exceptionVec_13 <= ~_GEN_3 & instMicroOp_uop_exceptionVec_13;
      instMicroOp_uop_exceptionVec_15 <= ~_GEN_3 & instMicroOp_uop_exceptionVec_15;
    end
    if (_GEN_45 & ~io_dtlb_resp_bits_miss)
      instMicroOp_paddr <= io_dtlb_resp_bits_paddr_0;
    if (_GEN_1 & (exception_va | exception_pa) & canTriggerException)
      instMicroOp_exceptionVaddr <= _vaddr_T_3;
    if (_GEN_7 & splitPtr_value == 3'h0)
      data_0 <= mergedData;
    else if (_GEN_37)
      data_0 <= io_in_bits_src_2;
    if (_GEN_7 & splitPtr_value == 3'h1)
      data_1 <= mergedData;
    else if (_GEN_38)
      data_1 <= io_in_bits_src_2;
    if (_GEN_7 & splitPtr_value == 3'h2)
      data_2 <= mergedData;
    else if (_GEN_39)
      data_2 <= io_in_bits_src_2;
    if (_GEN_7 & splitPtr_value == 3'h3)
      data_3 <= mergedData;
    else if (_GEN_40)
      data_3 <= io_in_bits_src_2;
    if (_GEN_7 & splitPtr_value == 3'h4)
      data_4 <= mergedData;
    else if (_GEN_41)
      data_4 <= io_in_bits_src_2;
    if (_GEN_7 & splitPtr_value == 3'h5)
      data_5 <= mergedData;
    else if (_GEN_42)
      data_5 <= io_in_bits_src_2;
    if (_GEN_7 & splitPtr_value == 3'h6)
      data_6 <= mergedData;
    else if (_GEN_43)
      data_6 <= io_in_bits_src_2;
    if (_GEN_7 & (&splitPtr_value))
      data_7 <= mergedData;
    else if (_GEN_44)
      data_7 <= io_in_bits_src_2;
    if (_GEN_37) begin
      uopq_0_uop_vecWen <= io_in_bits_uop_vecWen;
      uopq_0_uop_v0Wen <= io_in_bits_uop_v0Wen;
      uopq_0_uop_vpu_vuopIdx <= io_in_bits_uop_vpu_vuopIdx;
      uopq_0_uop_pdest <= io_in_bits_uop_pdest;
      uopq_0_uop_lqIdx_flag <= io_in_bits_uop_lqIdx_flag;
      uopq_0_uop_lqIdx_value <= io_in_bits_uop_lqIdx_value;
      uopq_0_uop_sqIdx_flag <= io_in_bits_uop_sqIdx_flag;
      uopq_0_uop_sqIdx_value <= io_in_bits_uop_sqIdx_value;
      stride_0 <= io_in_bits_src_1;
    end
    if (_GEN_38) begin
      uopq_1_uop_vecWen <= io_in_bits_uop_vecWen;
      uopq_1_uop_v0Wen <= io_in_bits_uop_v0Wen;
      uopq_1_uop_vpu_vuopIdx <= io_in_bits_uop_vpu_vuopIdx;
      uopq_1_uop_pdest <= io_in_bits_uop_pdest;
      uopq_1_uop_lqIdx_flag <= io_in_bits_uop_lqIdx_flag;
      uopq_1_uop_lqIdx_value <= io_in_bits_uop_lqIdx_value;
      uopq_1_uop_sqIdx_flag <= io_in_bits_uop_sqIdx_flag;
      uopq_1_uop_sqIdx_value <= io_in_bits_uop_sqIdx_value;
      stride_1 <= io_in_bits_src_1;
    end
    if (_GEN_39) begin
      uopq_2_uop_vecWen <= io_in_bits_uop_vecWen;
      uopq_2_uop_v0Wen <= io_in_bits_uop_v0Wen;
      uopq_2_uop_vpu_vuopIdx <= io_in_bits_uop_vpu_vuopIdx;
      uopq_2_uop_pdest <= io_in_bits_uop_pdest;
      uopq_2_uop_lqIdx_flag <= io_in_bits_uop_lqIdx_flag;
      uopq_2_uop_lqIdx_value <= io_in_bits_uop_lqIdx_value;
      uopq_2_uop_sqIdx_flag <= io_in_bits_uop_sqIdx_flag;
      uopq_2_uop_sqIdx_value <= io_in_bits_uop_sqIdx_value;
      stride_2 <= io_in_bits_src_1;
    end
    if (_GEN_40) begin
      uopq_3_uop_vecWen <= io_in_bits_uop_vecWen;
      uopq_3_uop_v0Wen <= io_in_bits_uop_v0Wen;
      uopq_3_uop_vpu_vuopIdx <= io_in_bits_uop_vpu_vuopIdx;
      uopq_3_uop_pdest <= io_in_bits_uop_pdest;
      uopq_3_uop_lqIdx_flag <= io_in_bits_uop_lqIdx_flag;
      uopq_3_uop_lqIdx_value <= io_in_bits_uop_lqIdx_value;
      uopq_3_uop_sqIdx_flag <= io_in_bits_uop_sqIdx_flag;
      uopq_3_uop_sqIdx_value <= io_in_bits_uop_sqIdx_value;
      stride_3 <= io_in_bits_src_1;
    end
    if (_GEN_41) begin
      uopq_4_uop_vecWen <= io_in_bits_uop_vecWen;
      uopq_4_uop_v0Wen <= io_in_bits_uop_v0Wen;
      uopq_4_uop_vpu_vuopIdx <= io_in_bits_uop_vpu_vuopIdx;
      uopq_4_uop_pdest <= io_in_bits_uop_pdest;
      uopq_4_uop_lqIdx_flag <= io_in_bits_uop_lqIdx_flag;
      uopq_4_uop_lqIdx_value <= io_in_bits_uop_lqIdx_value;
      uopq_4_uop_sqIdx_flag <= io_in_bits_uop_sqIdx_flag;
      uopq_4_uop_sqIdx_value <= io_in_bits_uop_sqIdx_value;
      stride_4 <= io_in_bits_src_1;
    end
    if (_GEN_42) begin
      uopq_5_uop_vecWen <= io_in_bits_uop_vecWen;
      uopq_5_uop_v0Wen <= io_in_bits_uop_v0Wen;
      uopq_5_uop_vpu_vuopIdx <= io_in_bits_uop_vpu_vuopIdx;
      uopq_5_uop_pdest <= io_in_bits_uop_pdest;
      uopq_5_uop_lqIdx_flag <= io_in_bits_uop_lqIdx_flag;
      uopq_5_uop_lqIdx_value <= io_in_bits_uop_lqIdx_value;
      uopq_5_uop_sqIdx_flag <= io_in_bits_uop_sqIdx_flag;
      uopq_5_uop_sqIdx_value <= io_in_bits_uop_sqIdx_value;
      stride_5 <= io_in_bits_src_1;
    end
    if (_GEN_43) begin
      uopq_6_uop_vecWen <= io_in_bits_uop_vecWen;
      uopq_6_uop_v0Wen <= io_in_bits_uop_v0Wen;
      uopq_6_uop_vpu_vuopIdx <= io_in_bits_uop_vpu_vuopIdx;
      uopq_6_uop_pdest <= io_in_bits_uop_pdest;
      uopq_6_uop_lqIdx_flag <= io_in_bits_uop_lqIdx_flag;
      uopq_6_uop_lqIdx_value <= io_in_bits_uop_lqIdx_value;
      uopq_6_uop_sqIdx_flag <= io_in_bits_uop_sqIdx_flag;
      uopq_6_uop_sqIdx_value <= io_in_bits_uop_sqIdx_value;
      stride_6 <= io_in_bits_src_1;
    end
    if (_GEN_44) begin
      uopq_7_uop_vecWen <= io_in_bits_uop_vecWen;
      uopq_7_uop_v0Wen <= io_in_bits_uop_v0Wen;
      uopq_7_uop_vpu_vuopIdx <= io_in_bits_uop_vpu_vuopIdx;
      uopq_7_uop_pdest <= io_in_bits_uop_pdest;
      uopq_7_uop_lqIdx_flag <= io_in_bits_uop_lqIdx_flag;
      uopq_7_uop_lqIdx_value <= io_in_bits_uop_lqIdx_value;
      uopq_7_uop_sqIdx_flag <= io_in_bits_uop_sqIdx_flag;
      uopq_7_uop_sqIdx_value <= io_in_bits_uop_sqIdx_value;
      stride_7 <= io_in_bits_src_1;
    end
  end // always @(posedge)
  wire [3:0]        _enqPtr_new_ptr_T_1 = 4'({enqPtr_flag, enqPtr_value} + 4'h1);
  wire [3:0]        _deqPtr_new_ptr_T_1 = 4'(_GEN_17 + 4'h1);
  wire [7:0]        _maxSegIdx_T = 8'(instMicroOp_vl - 8'h1);
  wire              _GEN_58 = segmentIdx == _maxSegIdx_T;
  wire [3:0]        _GEN_59 =
    _GEN_58 & fieldIdx == _GEN_2 | _GEN_58 & ~segmentActive ? 4'hA : 4'h3;
  wire [3:0]        _GEN_60 =
    state != 4'hA
    | (enqPtr_flag == deqPtr_flag
         ? {1'h0, 3'(enqPtr_value - deqPtr_value)}
         : 4'(4'({1'h0, enqPtr_value} - 4'h8) - {1'h0, deqPtr_value})) == 4'h0
      ? 4'h0
      : 4'hA;
  wire [15:0][3:0]  _GEN_61 =
    {{_GEN_60},
     {_GEN_60},
     {_GEN_60},
     {_GEN_60},
     {_GEN_60},
     {_GEN_60},
     {~(io_sbuffer_ready & io_sbuffer_valid_0) & segmentActive ? 4'h9 : _GEN_59},
     {_GEN_59},
     {io_rdcache_resp_valid
        ? (io_rdcache_resp_bits_miss | io_rdcache_s2_bank_conflict
             ? 4'h6
             : {3'h4, ~(instMicroOp_uop_fuType[31] | instMicroOp_uop_fuType[33])})
        : 4'h7},
     {{3'h3, io_rdcache_req_ready & io_rdcache_req_valid_0}},
     {exception_pa | exception_va
        ? 4'hA
        : instMicroOp_uop_fuType[31] | instMicroOp_uop_fuType[33] ? 4'h6 : 4'h9},
     {io_dtlb_resp_valid ? (io_dtlb_resp_bits_miss ? 4'h3 : 4'h5) : 4'h4},
     {segmentActive
        ? 4'h4
        : {3'h4, ~(instMicroOp_uop_fuType[31] | instMicroOp_uop_fuType[33])}},
     {{3'h1, io_flush_sbuffer_empty}},
     {{3'h1, io_flush_sbuffer_empty}},
     {{3'h0, enqPtr_flag ^ deqPtr_flag ^ enqPtr_value > deqPtr_value}}};
  wire [3:0]        stateNext = _GEN_61[state];
  wire              fieldActiveWirteFinish =
    io_sbuffer_ready & io_sbuffer_valid_0 & segmentActive;
  wire              segmentInactiveFinish =
    (_segmentInactiveFinish_T | _segmentInactiveFinish_T_1) & ~segmentActive;
  wire              _GEN_62 = _segmentInactiveFinish_T_1 & fieldActiveWirteFinish;
  wire              _GEN_63 = _fieldIdx_T & (_segmentInactiveFinish_T | _GEN_62);
  wire              _GEN_64 = segmentIdx != _maxSegIdx_T;
  always @(posedge clock or posedge reset) begin
    if (reset) begin
      instMicroOpValid <= 1'h0;
      enqPtr_flag <= 1'h0;
      enqPtr_value <= 3'h0;
      deqPtr_flag <= 1'h0;
      deqPtr_value <= 3'h0;
      segmentIdx <= 8'h0;
      fieldIdx <= 4'h0;
      segmentOffset <= 41'h0;
      splitPtr_flag <= 1'h0;
      splitPtr_value <= 3'h0;
      latchVaddr <= 41'h0;
      state <= 4'h0;
    end
    else begin
      instMicroOpValid <= (|stateNext) & (_GEN_3 | instMicroOpValid);
      if (io_in_valid) begin
        enqPtr_flag <= _enqPtr_new_ptr_T_1[3];
        enqPtr_value <= _enqPtr_new_ptr_T_1[2:0];
      end
      if (io_uopwriteback_valid_0) begin
        deqPtr_flag <= _deqPtr_new_ptr_T_1[3];
        deqPtr_value <= _deqPtr_new_ptr_T_1[2:0];
      end
      if (_GEN_3) begin
        segmentIdx <= 8'h0;
        fieldIdx <= 4'h0;
      end
      else begin
        if (_GEN_63 & _GEN_64)
          segmentIdx <= _segmentIdx_T_2[7:0];
        else if (segmentInactiveFinish & _GEN_64)
          segmentIdx <= _segmentIdx_T_2[7:0];
        if (_GEN_7 | _GEN_62) begin
          if (_fieldIdx_T)
            fieldIdx <= 4'h0;
          else
            fieldIdx <= 4'(fieldIdx + 4'h1);
        end
        else if (segmentInactiveFinish)
          fieldIdx <= 4'h0;
      end
      if (_GEN_63 | segmentInactiveFinish)
        segmentOffset <=
          41'(segmentOffset
              + (instMicroOp_uop_fuOpType[6:5] == 2'h0
                   ? {34'h0, {3'h0, 4'(_GEN_2 + 4'h1)} << instMicroOp_uop_vpu_veew}
                   : _GEN_4[stridePtr_value][40:0]));
      else if (_GEN_3)
        segmentOffset <= 41'h0;
      if (_segmentInactiveFinish_T | _segmentInactiveFinish_T_1
          & (fieldActiveWirteFinish | ~segmentActive)) begin
        splitPtr_flag <= splitPtrNext_flag;
        splitPtr_value <= splitPtrNext_value;
      end
      else if (_GEN_3) begin
        splitPtr_flag <= deqPtr_flag;
        splitPtr_value <= deqPtr_value;
      end
      if (_io_dtlb_req_valid_T)
        latchVaddr <= _vaddr_T_3;
      state <= stateNext;
    end
  end // always @(posedge, posedge)
  `ifdef ENABLE_INITIAL_REG_
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:422];
    initial begin
      `ifdef INIT_RANDOM_PROLOG_
        `INIT_RANDOM_PROLOG_
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT
        for (logic [8:0] i = 9'h0; i < 9'h1A7; i += 9'h1) begin
          _RANDOM[i] = `RANDOM;
        end
        instMicroOp_baseVaddr = {_RANDOM[9'h0], _RANDOM[9'h1][8:0]};
        instMicroOp_uop_exceptionVec_4 = _RANDOM[9'h4][0];
        instMicroOp_uop_exceptionVec_5 = _RANDOM[9'h4][1];
        instMicroOp_uop_exceptionVec_6 = _RANDOM[9'h4][2];
        instMicroOp_uop_exceptionVec_7 = _RANDOM[9'h4][3];
        instMicroOp_uop_exceptionVec_13 = _RANDOM[9'h4][9];
        instMicroOp_uop_exceptionVec_15 = _RANDOM[9'h4][11];
        instMicroOp_uop_fuType = {_RANDOM[9'h6][31:18], _RANDOM[9'h7][20:0]};
        instMicroOp_uop_fuOpType = _RANDOM[9'h7][29:21];
        instMicroOp_uop_vpu_vma = _RANDOM[9'hA][0];
        instMicroOp_uop_vpu_vta = _RANDOM[9'hA][1];
        instMicroOp_uop_vpu_vsew = _RANDOM[9'hA][3:2];
        instMicroOp_uop_vpu_vlmul = _RANDOM[9'hA][6:4];
        instMicroOp_uop_vpu_vm = _RANDOM[9'hA][15];
        instMicroOp_uop_vpu_vstart = _RANDOM[9'hA][23:16];
        instMicroOp_uop_vpu_nf = _RANDOM[9'hF][22:20];
        instMicroOp_uop_vpu_veew = _RANDOM[9'hF][24:23];
        instMicroOp_uop_robIdx_flag = _RANDOM[9'h13][30];
        instMicroOp_uop_robIdx_value = {_RANDOM[9'h13][31], _RANDOM[9'h14][6:0]};
        instMicroOp_paddr = {_RANDOM[9'h27][31:22], _RANDOM[9'h28][25:0]};
        instMicroOp_mask =
          {_RANDOM[9'h28][31:26],
           _RANDOM[9'h29],
           _RANDOM[9'h2A],
           _RANDOM[9'h2B],
           _RANDOM[9'h2C][25:0]};
        instMicroOp_alignedType = _RANDOM[9'h2C][28:26];
        instMicroOp_vl = {_RANDOM[9'h2C][31:29], _RANDOM[9'h2D][4:0]};
        instMicroOp_uopFlowNumMask = _RANDOM[9'h2D][20:13];
        instMicroOp_exceptionVaddr =
          {_RANDOM[9'h2D][31:29], _RANDOM[9'h2E], _RANDOM[9'h2F][5:0]};
        instMicroOp_isFof = _RANDOM[9'h2F][24];
        instMicroOpValid = _RANDOM[9'h2F][25];
        data_0 =
          {_RANDOM[9'h2F][31:26],
           _RANDOM[9'h30],
           _RANDOM[9'h31],
           _RANDOM[9'h32],
           _RANDOM[9'h33][25:0]};
        data_1 =
          {_RANDOM[9'h33][31:26],
           _RANDOM[9'h34],
           _RANDOM[9'h35],
           _RANDOM[9'h36],
           _RANDOM[9'h37][25:0]};
        data_2 =
          {_RANDOM[9'h37][31:26],
           _RANDOM[9'h38],
           _RANDOM[9'h39],
           _RANDOM[9'h3A],
           _RANDOM[9'h3B][25:0]};
        data_3 =
          {_RANDOM[9'h3B][31:26],
           _RANDOM[9'h3C],
           _RANDOM[9'h3D],
           _RANDOM[9'h3E],
           _RANDOM[9'h3F][25:0]};
        data_4 =
          {_RANDOM[9'h3F][31:26],
           _RANDOM[9'h40],
           _RANDOM[9'h41],
           _RANDOM[9'h42],
           _RANDOM[9'h43][25:0]};
        data_5 =
          {_RANDOM[9'h43][31:26],
           _RANDOM[9'h44],
           _RANDOM[9'h45],
           _RANDOM[9'h46],
           _RANDOM[9'h47][25:0]};
        data_6 =
          {_RANDOM[9'h47][31:26],
           _RANDOM[9'h48],
           _RANDOM[9'h49],
           _RANDOM[9'h4A],
           _RANDOM[9'h4B][25:0]};
        data_7 =
          {_RANDOM[9'h4B][31:26],
           _RANDOM[9'h4C],
           _RANDOM[9'h4D],
           _RANDOM[9'h4E],
           _RANDOM[9'h4F][25:0]};
        uopq_0_uop_vecWen = _RANDOM[9'h56][17];
        uopq_0_uop_v0Wen = _RANDOM[9'h56][18];
        uopq_0_uop_vpu_vuopIdx = _RANDOM[9'h59][27:21];
        uopq_0_uop_pdest = {_RANDOM[9'h61][31:27], _RANDOM[9'h62][2:0]};
        uopq_0_uop_lqIdx_flag = _RANDOM[9'h75][17];
        uopq_0_uop_lqIdx_value = _RANDOM[9'h75][24:18];
        uopq_0_uop_sqIdx_flag = _RANDOM[9'h75][25];
        uopq_0_uop_sqIdx_value = _RANDOM[9'h75][31:26];
        uopq_1_uop_vecWen = _RANDOM[9'h7C][30];
        uopq_1_uop_v0Wen = _RANDOM[9'h7C][31];
        uopq_1_uop_vpu_vuopIdx = _RANDOM[9'h80][8:2];
        uopq_1_uop_pdest = _RANDOM[9'h88][15:8];
        uopq_1_uop_lqIdx_flag = _RANDOM[9'h9B][30];
        uopq_1_uop_lqIdx_value = {_RANDOM[9'h9B][31], _RANDOM[9'h9C][5:0]};
        uopq_1_uop_sqIdx_flag = _RANDOM[9'h9C][6];
        uopq_1_uop_sqIdx_value = _RANDOM[9'h9C][12:7];
        uopq_2_uop_vecWen = _RANDOM[9'hA3][11];
        uopq_2_uop_v0Wen = _RANDOM[9'hA3][12];
        uopq_2_uop_vpu_vuopIdx = _RANDOM[9'hA6][21:15];
        uopq_2_uop_pdest = _RANDOM[9'hAE][28:21];
        uopq_2_uop_lqIdx_flag = _RANDOM[9'hC2][11];
        uopq_2_uop_lqIdx_value = _RANDOM[9'hC2][18:12];
        uopq_2_uop_sqIdx_flag = _RANDOM[9'hC2][19];
        uopq_2_uop_sqIdx_value = _RANDOM[9'hC2][25:20];
        uopq_3_uop_vecWen = _RANDOM[9'hC9][24];
        uopq_3_uop_v0Wen = _RANDOM[9'hC9][25];
        uopq_3_uop_vpu_vuopIdx = {_RANDOM[9'hCC][31:28], _RANDOM[9'hCD][2:0]};
        uopq_3_uop_pdest = _RANDOM[9'hD5][9:2];
        uopq_3_uop_lqIdx_flag = _RANDOM[9'hE8][24];
        uopq_3_uop_lqIdx_value = _RANDOM[9'hE8][31:25];
        uopq_3_uop_sqIdx_flag = _RANDOM[9'hE9][0];
        uopq_3_uop_sqIdx_value = _RANDOM[9'hE9][6:1];
        uopq_4_uop_vecWen = _RANDOM[9'hF0][5];
        uopq_4_uop_v0Wen = _RANDOM[9'hF0][6];
        uopq_4_uop_vpu_vuopIdx = _RANDOM[9'hF3][15:9];
        uopq_4_uop_pdest = _RANDOM[9'hFB][22:15];
        uopq_4_uop_lqIdx_flag = _RANDOM[9'h10F][5];
        uopq_4_uop_lqIdx_value = _RANDOM[9'h10F][12:6];
        uopq_4_uop_sqIdx_flag = _RANDOM[9'h10F][13];
        uopq_4_uop_sqIdx_value = _RANDOM[9'h10F][19:14];
        uopq_5_uop_vecWen = _RANDOM[9'h116][18];
        uopq_5_uop_v0Wen = _RANDOM[9'h116][19];
        uopq_5_uop_vpu_vuopIdx = _RANDOM[9'h119][28:22];
        uopq_5_uop_pdest = {_RANDOM[9'h121][31:28], _RANDOM[9'h122][3:0]};
        uopq_5_uop_lqIdx_flag = _RANDOM[9'h135][18];
        uopq_5_uop_lqIdx_value = _RANDOM[9'h135][25:19];
        uopq_5_uop_sqIdx_flag = _RANDOM[9'h135][26];
        uopq_5_uop_sqIdx_value = {_RANDOM[9'h135][31:27], _RANDOM[9'h136][0]};
        uopq_6_uop_vecWen = _RANDOM[9'h13C][31];
        uopq_6_uop_v0Wen = _RANDOM[9'h13D][0];
        uopq_6_uop_vpu_vuopIdx = _RANDOM[9'h140][9:3];
        uopq_6_uop_pdest = _RANDOM[9'h148][16:9];
        uopq_6_uop_lqIdx_flag = _RANDOM[9'h15B][31];
        uopq_6_uop_lqIdx_value = _RANDOM[9'h15C][6:0];
        uopq_6_uop_sqIdx_flag = _RANDOM[9'h15C][7];
        uopq_6_uop_sqIdx_value = _RANDOM[9'h15C][13:8];
        uopq_7_uop_vecWen = _RANDOM[9'h163][12];
        uopq_7_uop_v0Wen = _RANDOM[9'h163][13];
        uopq_7_uop_vpu_vuopIdx = _RANDOM[9'h166][22:16];
        uopq_7_uop_pdest = _RANDOM[9'h16E][29:22];
        uopq_7_uop_lqIdx_flag = _RANDOM[9'h182][12];
        uopq_7_uop_lqIdx_value = _RANDOM[9'h182][19:13];
        uopq_7_uop_sqIdx_flag = _RANDOM[9'h182][20];
        uopq_7_uop_sqIdx_value = _RANDOM[9'h182][26:21];
        stride_0 =
          {_RANDOM[9'h183][31:2],
           _RANDOM[9'h184],
           _RANDOM[9'h185],
           _RANDOM[9'h186],
           _RANDOM[9'h187][1:0]};
        stride_1 =
          {_RANDOM[9'h187][31:2],
           _RANDOM[9'h188],
           _RANDOM[9'h189],
           _RANDOM[9'h18A],
           _RANDOM[9'h18B][1:0]};
        stride_2 =
          {_RANDOM[9'h18B][31:2],
           _RANDOM[9'h18C],
           _RANDOM[9'h18D],
           _RANDOM[9'h18E],
           _RANDOM[9'h18F][1:0]};
        stride_3 =
          {_RANDOM[9'h18F][31:2],
           _RANDOM[9'h190],
           _RANDOM[9'h191],
           _RANDOM[9'h192],
           _RANDOM[9'h193][1:0]};
        stride_4 =
          {_RANDOM[9'h193][31:2],
           _RANDOM[9'h194],
           _RANDOM[9'h195],
           _RANDOM[9'h196],
           _RANDOM[9'h197][1:0]};
        stride_5 =
          {_RANDOM[9'h197][31:2],
           _RANDOM[9'h198],
           _RANDOM[9'h199],
           _RANDOM[9'h19A],
           _RANDOM[9'h19B][1:0]};
        stride_6 =
          {_RANDOM[9'h19B][31:2],
           _RANDOM[9'h19C],
           _RANDOM[9'h19D],
           _RANDOM[9'h19E],
           _RANDOM[9'h19F][1:0]};
        stride_7 =
          {_RANDOM[9'h19F][31:2],
           _RANDOM[9'h1A0],
           _RANDOM[9'h1A1],
           _RANDOM[9'h1A2],
           _RANDOM[9'h1A3][1:0]};
        enqPtr_flag = _RANDOM[9'h1A3][10];
        enqPtr_value = _RANDOM[9'h1A3][13:11];
        deqPtr_flag = _RANDOM[9'h1A3][14];
        deqPtr_value = _RANDOM[9'h1A3][17:15];
        segmentIdx = _RANDOM[9'h1A3][25:18];
        fieldIdx = _RANDOM[9'h1A3][29:26];
        segmentOffset = {_RANDOM[9'h1A3][31:30], _RANDOM[9'h1A4], _RANDOM[9'h1A5][6:0]};
        splitPtr_flag = _RANDOM[9'h1A5][7];
        splitPtr_value = _RANDOM[9'h1A5][10:8];
        latchVaddr = {_RANDOM[9'h1A5][31:11], _RANDOM[9'h1A6][19:0]};
        state = _RANDOM[9'h1A6][23:20];
      `endif // RANDOMIZE_REG_INIT
      if (reset) begin
        instMicroOpValid = 1'h0;
        enqPtr_flag = 1'h0;
        enqPtr_value = 3'h0;
        deqPtr_flag = 1'h0;
        deqPtr_value = 3'h0;
        segmentIdx = 8'h0;
        fieldIdx = 4'h0;
        segmentOffset = 41'h0;
        splitPtr_flag = 1'h0;
        splitPtr_value = 3'h0;
        latchVaddr = 41'h0;
        state = 4'h0;
      end
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_uopwriteback_valid = io_uopwriteback_valid_0;
  assign io_uopwriteback_bits_uop_exceptionVec_4 = instMicroOp_uop_exceptionVec_4;
  assign io_uopwriteback_bits_uop_exceptionVec_5 = instMicroOp_uop_exceptionVec_5;
  assign io_uopwriteback_bits_uop_exceptionVec_6 = instMicroOp_uop_exceptionVec_6;
  assign io_uopwriteback_bits_uop_exceptionVec_7 = instMicroOp_uop_exceptionVec_7;
  assign io_uopwriteback_bits_uop_exceptionVec_13 = instMicroOp_uop_exceptionVec_13;
  assign io_uopwriteback_bits_uop_exceptionVec_15 = instMicroOp_uop_exceptionVec_15;
  assign io_uopwriteback_bits_uop_fuOpType = instMicroOp_uop_fuOpType;
  assign io_uopwriteback_bits_uop_vecWen = _GEN_8[deqPtr_value];
  assign io_uopwriteback_bits_uop_v0Wen = _GEN_9[deqPtr_value];
  assign io_uopwriteback_bits_uop_vpu_vma = instMicroOp_uop_vpu_vma;
  assign io_uopwriteback_bits_uop_vpu_vta = instMicroOp_uop_vpu_vta;
  assign io_uopwriteback_bits_uop_vpu_vsew = instMicroOp_uop_vpu_vsew;
  assign io_uopwriteback_bits_uop_vpu_vm = instMicroOp_uop_vpu_vm;
  assign io_uopwriteback_bits_uop_vpu_vmask = {112'h0, _GEN_34[vdIdxInField]};
  assign io_uopwriteback_bits_uop_vpu_vl = instMicroOp_vl;
  assign io_uopwriteback_bits_uop_vpu_veew = instMicroOp_uop_vpu_veew;
  assign io_uopwriteback_bits_uop_pdest = _GEN_12[deqPtr_value];
  assign io_uopwriteback_bits_uop_robIdx_flag = instMicroOp_uop_robIdx_flag;
  assign io_uopwriteback_bits_uop_robIdx_value = instMicroOp_uop_robIdx_value;
  assign io_uopwriteback_bits_data = _GEN_5[deqPtr_value];
  assign io_uopwriteback_bits_vdIdxInField = vdIdxInField;
  assign io_rdcache_req_valid = io_rdcache_req_valid_0;
  assign io_rdcache_req_bits_vaddr = latchVaddr;
  assign io_rdcache_s1_paddr_dup_lsu = instMicroOp_paddr;
  assign io_rdcache_s1_paddr_dup_dcache = instMicroOp_paddr;
  assign io_sbuffer_valid = io_sbuffer_valid_0;
  assign io_sbuffer_bits_vaddr = latchVaddr;
  assign io_sbuffer_bits_data =
    (_flowData_T_15 ? {2{{2{{2{{2{splitData[7:0]}}}}}}}} : 128'h0)
    | (_flowData_T_16 ? {2{{2{{2{splitData[15:0]}}}}}} : 128'h0)
    | (_flowData_T_17 ? {2{{2{splitData[31:0]}}}} : 128'h0)
    | (_flowData_T_18 ? {2{splitData[63:0]}} : 128'h0)
    | (_flowData_T_19 ? splitData : 128'h0);
  assign io_sbuffer_bits_mask = _wmask_T_13[15:0] & {16{segmentActive}};
  assign io_sbuffer_bits_addr = instMicroOp_paddr;
  assign io_sbuffer_bits_vecValid = _segmentInactiveFinish_T_1 & segmentActive;
  assign io_dtlb_req_valid = _io_dtlb_req_valid_T & segmentActive;
  assign io_dtlb_req_bits_vaddr = _vaddr_T_3;
  assign io_dtlb_req_bits_cmd =
    {2'h0, ~(instMicroOp_uop_fuType[31] | instMicroOp_uop_fuType[33])};
  assign io_dtlb_req_bits_debug_robIdx_flag = instMicroOp_uop_robIdx_flag;
  assign io_dtlb_req_bits_debug_robIdx_value = instMicroOp_uop_robIdx_value;
  assign io_flush_sbuffer_valid = ~io_flush_sbuffer_empty & state == 4'h1;
  assign io_feedback_valid =
    _io_exceptionInfo_valid_T
    & _io_exceptionInfo_valid_T_4 != _io_exceptionInfo_valid_T_5;
  assign io_feedback_bits_sqIdx_flag = _GEN_15[deqPtr_value];
  assign io_feedback_bits_sqIdx_value = _GEN_16[deqPtr_value];
  assign io_feedback_bits_lqIdx_flag = _GEN_13[deqPtr_value];
  assign io_feedback_bits_lqIdx_value = _GEN_14[deqPtr_value];
  assign io_exceptionInfo_valid =
    _io_exceptionInfo_valid_T
    & (|{instMicroOp_uop_exceptionVec_15,
         instMicroOp_uop_exceptionVec_13,
         instMicroOp_uop_exceptionVec_7,
         instMicroOp_uop_exceptionVec_6,
         instMicroOp_uop_exceptionVec_5,
         instMicroOp_uop_exceptionVec_4})
    & _io_exceptionInfo_valid_T_4 != _io_exceptionInfo_valid_T_5;
  assign io_exceptionInfo_bits_vaddr = instMicroOp_exceptionVaddr;
endmodule

