// Generated by CIRCT firtool-1.62.0
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

module SubDirectory(
  input         clock,
  input         reset,
  output        io_read_ready,
  input         io_read_valid,
  input  [16:0] io_read_bits_tag,
  input  [10:0] io_read_bits_set,
  output        io_resp_bits_hit,
  output [3:0]  io_resp_bits_way,
  output [16:0] io_resp_bits_tag,
  output [1:0]  io_resp_bits_dir_0_state,
  output [1:0]  io_resp_bits_dir_1_state,
  output        io_resp_bits_error,
  input         io_tag_w_valid,
  input  [16:0] io_tag_w_bits_tag,
  input  [10:0] io_tag_w_bits_set,
  input  [3:0]  io_tag_w_bits_way,
  input         io_dir_w_valid,
  input  [10:0] io_dir_w_bits_set,
  input  [3:0]  io_dir_w_bits_way,
  input  [1:0]  io_dir_w_bits_dir_0_state,
  input  [1:0]  io_dir_w_bits_dir_1_state
);

  wire              _lfsr_prng_io_out_0;
  wire              _lfsr_prng_io_out_1;
  wire              _lfsr_prng_io_out_2;
  wire              _lfsr_prng_io_out_3;
  wire              _lfsr_prng_io_out_4;
  wire              _lfsr_prng_io_out_5;
  wire              _lfsr_prng_io_out_6;
  wire [5:0]        _eccArray_io_r_resp_data_0;
  wire [5:0]        _eccArray_io_r_resp_data_1;
  wire [5:0]        _eccArray_io_r_resp_data_2;
  wire [5:0]        _eccArray_io_r_resp_data_3;
  wire [5:0]        _eccArray_io_r_resp_data_4;
  wire [5:0]        _eccArray_io_r_resp_data_5;
  wire [5:0]        _eccArray_io_r_resp_data_6;
  wire [5:0]        _eccArray_io_r_resp_data_7;
  wire [5:0]        _eccArray_io_r_resp_data_8;
  wire [5:0]        _eccArray_io_r_resp_data_9;
  wire [16:0]       _tagArray_io_r_resp_data_0;
  wire [16:0]       _tagArray_io_r_resp_data_1;
  wire [16:0]       _tagArray_io_r_resp_data_2;
  wire [16:0]       _tagArray_io_r_resp_data_3;
  wire [16:0]       _tagArray_io_r_resp_data_4;
  wire [16:0]       _tagArray_io_r_resp_data_5;
  wire [16:0]       _tagArray_io_r_resp_data_6;
  wire [16:0]       _tagArray_io_r_resp_data_7;
  wire [16:0]       _tagArray_io_r_resp_data_8;
  wire [16:0]       _tagArray_io_r_resp_data_9;
  wire              _ClockGate_Q;
  wire [1:0]        _metaArray_io_r_resp_data_0_0_state;
  wire [1:0]        _metaArray_io_r_resp_data_0_1_state;
  wire [1:0]        _metaArray_io_r_resp_data_1_0_state;
  wire [1:0]        _metaArray_io_r_resp_data_1_1_state;
  wire [1:0]        _metaArray_io_r_resp_data_2_0_state;
  wire [1:0]        _metaArray_io_r_resp_data_2_1_state;
  wire [1:0]        _metaArray_io_r_resp_data_3_0_state;
  wire [1:0]        _metaArray_io_r_resp_data_3_1_state;
  wire [1:0]        _metaArray_io_r_resp_data_4_0_state;
  wire [1:0]        _metaArray_io_r_resp_data_4_1_state;
  wire [1:0]        _metaArray_io_r_resp_data_5_0_state;
  wire [1:0]        _metaArray_io_r_resp_data_5_1_state;
  wire [1:0]        _metaArray_io_r_resp_data_6_0_state;
  wire [1:0]        _metaArray_io_r_resp_data_6_1_state;
  wire [1:0]        _metaArray_io_r_resp_data_7_0_state;
  wire [1:0]        _metaArray_io_r_resp_data_7_1_state;
  wire [1:0]        _metaArray_io_r_resp_data_8_0_state;
  wire [1:0]        _metaArray_io_r_resp_data_8_1_state;
  wire [1:0]        _metaArray_io_r_resp_data_9_0_state;
  wire [1:0]        _metaArray_io_r_resp_data_9_1_state;
  reg               resetFinish;
  reg  [10:0]       resetIdx;
  reg               clk_en;
  wire              io_read_ready_0 = ~io_tag_w_valid & ~io_dir_w_valid & resetFinish;
  wire [16:0]       _syndromeUInt_T = io_tag_w_bits_tag & 17'hAD5B;
  wire [16:0]       _syndromeUInt_T_3 = io_tag_w_bits_tag & 17'h1366D;
  wire [16:0]       _syndromeUInt_T_6 = io_tag_w_bits_tag & 17'h1C78E;
  wire [16:0]       _syndromeUInt_T_9 = io_tag_w_bits_tag & 17'h7F0;
  wire [16:0]       _syndromeUInt_T_12 = io_tag_w_bits_tag & 17'h1F800;
  wire [5:0]        _GEN =
    {^{^_syndromeUInt_T_12,
       ^_syndromeUInt_T_9,
       ^_syndromeUInt_T_6,
       ^_syndromeUInt_T_3,
       ^_syndromeUInt_T,
       io_tag_w_bits_tag},
     ^_syndromeUInt_T_12,
     ^_syndromeUInt_T_9,
     ^_syndromeUInt_T_6,
     ^_syndromeUInt_T_3,
     ^_syndromeUInt_T};
  wire [15:0]       _GEN_0 = 16'h1 << io_tag_w_bits_way;
  wire              _metas_T = io_read_ready_0 & io_read_valid;
  reg  [16:0]       reqReg_tag;
  reg               reqValidReg;
  reg               reqValidReg_REG;
  reg               hit_s2;
  reg  [3:0]        way_s2;
  reg  [1:0]        metaAll_s2_0_0_state;
  reg  [1:0]        metaAll_s2_0_1_state;
  reg  [1:0]        metaAll_s2_1_0_state;
  reg  [1:0]        metaAll_s2_1_1_state;
  reg  [1:0]        metaAll_s2_2_0_state;
  reg  [1:0]        metaAll_s2_2_1_state;
  reg  [1:0]        metaAll_s2_3_0_state;
  reg  [1:0]        metaAll_s2_3_1_state;
  reg  [1:0]        metaAll_s2_4_0_state;
  reg  [1:0]        metaAll_s2_4_1_state;
  reg  [1:0]        metaAll_s2_5_0_state;
  reg  [1:0]        metaAll_s2_5_1_state;
  reg  [1:0]        metaAll_s2_6_0_state;
  reg  [1:0]        metaAll_s2_6_1_state;
  reg  [1:0]        metaAll_s2_7_0_state;
  reg  [1:0]        metaAll_s2_7_1_state;
  reg  [1:0]        metaAll_s2_8_0_state;
  reg  [1:0]        metaAll_s2_8_1_state;
  reg  [1:0]        metaAll_s2_9_0_state;
  reg  [1:0]        metaAll_s2_9_1_state;
  reg  [16:0]       tagAll_s2_0;
  reg  [16:0]       tagAll_s2_1;
  reg  [16:0]       tagAll_s2_2;
  reg  [16:0]       tagAll_s2_3;
  reg  [16:0]       tagAll_s2_4;
  reg  [16:0]       tagAll_s2_5;
  reg  [16:0]       tagAll_s2_6;
  reg  [16:0]       tagAll_s2_7;
  reg  [16:0]       tagAll_s2_8;
  reg  [16:0]       tagAll_s2_9;
  reg               errorAll_s2_0;
  reg               errorAll_s2_1;
  reg               errorAll_s2_2;
  reg               errorAll_s2_3;
  reg               errorAll_s2_4;
  reg               errorAll_s2_5;
  reg               errorAll_s2_6;
  reg               errorAll_s2_7;
  reg               errorAll_s2_8;
  reg               errorAll_s2_9;
  wire [15:0][1:0]  _GEN_1 =
    {{metaAll_s2_0_0_state},
     {metaAll_s2_0_0_state},
     {metaAll_s2_0_0_state},
     {metaAll_s2_0_0_state},
     {metaAll_s2_0_0_state},
     {metaAll_s2_0_0_state},
     {metaAll_s2_9_0_state},
     {metaAll_s2_8_0_state},
     {metaAll_s2_7_0_state},
     {metaAll_s2_6_0_state},
     {metaAll_s2_5_0_state},
     {metaAll_s2_4_0_state},
     {metaAll_s2_3_0_state},
     {metaAll_s2_2_0_state},
     {metaAll_s2_1_0_state},
     {metaAll_s2_0_0_state}};
  wire [15:0][1:0]  _GEN_2 =
    {{metaAll_s2_0_1_state},
     {metaAll_s2_0_1_state},
     {metaAll_s2_0_1_state},
     {metaAll_s2_0_1_state},
     {metaAll_s2_0_1_state},
     {metaAll_s2_0_1_state},
     {metaAll_s2_9_1_state},
     {metaAll_s2_8_1_state},
     {metaAll_s2_7_1_state},
     {metaAll_s2_6_1_state},
     {metaAll_s2_5_1_state},
     {metaAll_s2_4_1_state},
     {metaAll_s2_3_1_state},
     {metaAll_s2_2_1_state},
     {metaAll_s2_1_1_state},
     {metaAll_s2_0_1_state}};
  wire [15:0][16:0] _GEN_3 =
    {{tagAll_s2_0},
     {tagAll_s2_0},
     {tagAll_s2_0},
     {tagAll_s2_0},
     {tagAll_s2_0},
     {tagAll_s2_0},
     {tagAll_s2_9},
     {tagAll_s2_8},
     {tagAll_s2_7},
     {tagAll_s2_6},
     {tagAll_s2_5},
     {tagAll_s2_4},
     {tagAll_s2_3},
     {tagAll_s2_2},
     {tagAll_s2_1},
     {tagAll_s2_0}};
  wire [15:0]       _GEN_4 =
    {{errorAll_s2_0},
     {errorAll_s2_0},
     {errorAll_s2_0},
     {errorAll_s2_0},
     {errorAll_s2_0},
     {errorAll_s2_0},
     {errorAll_s2_9},
     {errorAll_s2_8},
     {errorAll_s2_7},
     {errorAll_s2_6},
     {errorAll_s2_5},
     {errorAll_s2_4},
     {errorAll_s2_3},
     {errorAll_s2_2},
     {errorAll_s2_1},
     {errorAll_s2_0}};
  wire [1:0]        _GEN_5 = resetFinish ? io_dir_w_bits_dir_0_state : 2'h0;
  wire [1:0]        _GEN_6 = resetFinish ? io_dir_w_bits_dir_1_state : 2'h0;
  wire [15:0]       _GEN_7 = 16'h1 << io_dir_w_bits_way;
  reg               resetMask;
  wire              hitVec_1 =
    _tagArray_io_r_resp_data_1 == reqReg_tag
    & (|{|_metaArray_io_r_resp_data_1_0_state, |_metaArray_io_r_resp_data_1_1_state});
  wire              hitVec_2 =
    _tagArray_io_r_resp_data_2 == reqReg_tag
    & (|{|_metaArray_io_r_resp_data_2_0_state, |_metaArray_io_r_resp_data_2_1_state});
  wire              hitVec_3 =
    _tagArray_io_r_resp_data_3 == reqReg_tag
    & (|{|_metaArray_io_r_resp_data_3_0_state, |_metaArray_io_r_resp_data_3_1_state});
  wire              hitVec_4 =
    _tagArray_io_r_resp_data_4 == reqReg_tag
    & (|{|_metaArray_io_r_resp_data_4_0_state, |_metaArray_io_r_resp_data_4_1_state});
  wire              hitVec_5 =
    _tagArray_io_r_resp_data_5 == reqReg_tag
    & (|{|_metaArray_io_r_resp_data_5_0_state, |_metaArray_io_r_resp_data_5_1_state});
  wire              hitVec_6 =
    _tagArray_io_r_resp_data_6 == reqReg_tag
    & (|{|_metaArray_io_r_resp_data_6_0_state, |_metaArray_io_r_resp_data_6_1_state});
  wire              hitVec_7 =
    _tagArray_io_r_resp_data_7 == reqReg_tag
    & (|{|_metaArray_io_r_resp_data_7_0_state, |_metaArray_io_r_resp_data_7_1_state});
  wire              hitVec_8 =
    _tagArray_io_r_resp_data_8 == reqReg_tag
    & (|{|_metaArray_io_r_resp_data_8_0_state, |_metaArray_io_r_resp_data_8_1_state});
  wire              hitVec_9 =
    _tagArray_io_r_resp_data_9 == reqReg_tag
    & (|{|_metaArray_io_r_resp_data_9_0_state, |_metaArray_io_r_resp_data_9_1_state});
  wire [2:0]        _hitWay_T_4 =
    {hitVec_7, hitVec_6, hitVec_5} | {hitVec_3, hitVec_2, hitVec_9 | hitVec_1};
  wire [6:0]        _replaceWay_T =
    {_lfsr_prng_io_out_6,
     _lfsr_prng_io_out_5,
     _lfsr_prng_io_out_4,
     _lfsr_prng_io_out_3,
     _lfsr_prng_io_out_2,
     _lfsr_prng_io_out_1,
     _lfsr_prng_io_out_0};
  wire [1:0]        _invalid_vec_T_2 =
    {_metaArray_io_r_resp_data_0_0_state == 2'h0,
     _metaArray_io_r_resp_data_0_1_state == 2'h0};
  wire [1:0]        _invalid_vec_T_5 =
    {_metaArray_io_r_resp_data_1_0_state == 2'h0,
     _metaArray_io_r_resp_data_1_1_state == 2'h0};
  wire [1:0]        _invalid_vec_T_8 =
    {_metaArray_io_r_resp_data_2_0_state == 2'h0,
     _metaArray_io_r_resp_data_2_1_state == 2'h0};
  wire [1:0]        _invalid_vec_T_11 =
    {_metaArray_io_r_resp_data_3_0_state == 2'h0,
     _metaArray_io_r_resp_data_3_1_state == 2'h0};
  wire [1:0]        _invalid_vec_T_14 =
    {_metaArray_io_r_resp_data_4_0_state == 2'h0,
     _metaArray_io_r_resp_data_4_1_state == 2'h0};
  wire [1:0]        _invalid_vec_T_17 =
    {_metaArray_io_r_resp_data_5_0_state == 2'h0,
     _metaArray_io_r_resp_data_5_1_state == 2'h0};
  wire [1:0]        _invalid_vec_T_20 =
    {_metaArray_io_r_resp_data_6_0_state == 2'h0,
     _metaArray_io_r_resp_data_6_1_state == 2'h0};
  wire [1:0]        _invalid_vec_T_23 =
    {_metaArray_io_r_resp_data_7_0_state == 2'h0,
     _metaArray_io_r_resp_data_7_1_state == 2'h0};
  wire [1:0]        _invalid_vec_T_26 =
    {_metaArray_io_r_resp_data_8_0_state == 2'h0,
     _metaArray_io_r_resp_data_8_1_state == 2'h0};
  wire              _way_T = (&_invalid_vec_T_2) | (&_invalid_vec_T_5);
  wire [9:0]        _hit_s1_T =
    {_tagArray_io_r_resp_data_0 == reqReg_tag
       & (|{|_metaArray_io_r_resp_data_0_0_state, |_metaArray_io_r_resp_data_0_1_state}),
     hitVec_1,
     hitVec_2,
     hitVec_3,
     hitVec_4,
     hitVec_5,
     hitVec_6,
     hitVec_7,
     hitVec_8,
     hitVec_9};
  always @(posedge clock or posedge reset) begin
    if (reset) begin
      resetFinish <= 1'h0;
      resetIdx <= 11'h7FF;
      clk_en <= 1'h0;
      reqValidReg <= 1'h0;
      hit_s2 <= 1'h0;
      way_s2 <= 4'h0;
      resetMask <= 1'h0;
    end
    else begin
      resetFinish <= resetIdx == 11'h0 & resetMask | resetFinish;
      if (~resetFinish & resetMask)
        resetIdx <= 11'(resetIdx - 11'h1);
      clk_en <= ~clk_en;
      reqValidReg <= reqValidReg_REG;
      if (reqValidReg) begin
        hit_s2 <= |_hit_s1_T;
        way_s2 <=
          (|_hit_s1_T)
            ? {|{hitVec_9, hitVec_8},
               |{hitVec_7, hitVec_6, hitVec_5, hitVec_4},
               |(_hitWay_T_4[2:1]),
               _hitWay_T_4[2] | _hitWay_T_4[0]}
            : (|{&_invalid_vec_T_2,
                 &_invalid_vec_T_5,
                 &_invalid_vec_T_8,
                 &_invalid_vec_T_11,
                 &_invalid_vec_T_14,
                 &_invalid_vec_T_17,
                 &_invalid_vec_T_20,
                 &_invalid_vec_T_23,
                 &_invalid_vec_T_26,
                 &{_metaArray_io_r_resp_data_9_0_state == 2'h0,
                   _metaArray_io_r_resp_data_9_1_state == 2'h0}})
                ? (_way_T | (&_invalid_vec_T_8) | (&_invalid_vec_T_11)
                   | (&_invalid_vec_T_14)
                     ? (_way_T
                          ? {3'h0, ~(&_invalid_vec_T_2)}
                          : (&_invalid_vec_T_8)
                              ? 4'h2
                              : (&_invalid_vec_T_11) ? 4'h3 : 4'h4)
                     : (&_invalid_vec_T_17) | (&_invalid_vec_T_20)
                         ? ((&_invalid_vec_T_17) ? 4'h5 : 4'h6)
                         : (&_invalid_vec_T_23) ? 4'h7 : {3'h4, ~(&_invalid_vec_T_26)})
                : _replaceWay_T < 7'hC
                    ? 4'h0
                    : _replaceWay_T < 7'h19
                        ? 4'h1
                        : _replaceWay_T < 7'h26
                            ? 4'h2
                            : _replaceWay_T < 7'h33
                                ? 4'h3
                                : _lfsr_prng_io_out_6
                                    ? (_replaceWay_T < 7'h4C
                                         ? 4'h5
                                         : _replaceWay_T < 7'h59
                                             ? 4'h6
                                             : _replaceWay_T < 7'h66
                                                 ? 4'h7
                                                 : {3'h4, _replaceWay_T > 7'h72})
                                    : 4'h4;
      end
      resetMask <= 1'(resetMask - 1'h1);
    end
  end // always @(posedge, posedge)
  wire [22:0]       _errorAll_s1_T =
    {_eccArray_io_r_resp_data_0, _tagArray_io_r_resp_data_0};
  wire [22:0]       _errorAll_s1_T_3 =
    {_eccArray_io_r_resp_data_1, _tagArray_io_r_resp_data_1};
  wire [22:0]       _errorAll_s1_T_6 =
    {_eccArray_io_r_resp_data_2, _tagArray_io_r_resp_data_2};
  wire [22:0]       _errorAll_s1_T_9 =
    {_eccArray_io_r_resp_data_3, _tagArray_io_r_resp_data_3};
  wire [22:0]       _errorAll_s1_T_12 =
    {_eccArray_io_r_resp_data_4, _tagArray_io_r_resp_data_4};
  wire [22:0]       _errorAll_s1_T_15 =
    {_eccArray_io_r_resp_data_5, _tagArray_io_r_resp_data_5};
  wire [22:0]       _errorAll_s1_T_18 =
    {_eccArray_io_r_resp_data_6, _tagArray_io_r_resp_data_6};
  wire [22:0]       _errorAll_s1_T_21 =
    {_eccArray_io_r_resp_data_7, _tagArray_io_r_resp_data_7};
  wire [22:0]       _errorAll_s1_T_24 =
    {_eccArray_io_r_resp_data_8, _tagArray_io_r_resp_data_8};
  wire [22:0]       _errorAll_s1_T_27 =
    {_eccArray_io_r_resp_data_9, _tagArray_io_r_resp_data_9};
  always @(posedge clock) begin
    if (_metas_T)
      reqReg_tag <= io_read_bits_tag;
    reqValidReg_REG <= _metas_T;
    if (reqValidReg) begin
      metaAll_s2_0_0_state <= _metaArray_io_r_resp_data_0_0_state;
      metaAll_s2_0_1_state <= _metaArray_io_r_resp_data_0_1_state;
      metaAll_s2_1_0_state <= _metaArray_io_r_resp_data_1_0_state;
      metaAll_s2_1_1_state <= _metaArray_io_r_resp_data_1_1_state;
      metaAll_s2_2_0_state <= _metaArray_io_r_resp_data_2_0_state;
      metaAll_s2_2_1_state <= _metaArray_io_r_resp_data_2_1_state;
      metaAll_s2_3_0_state <= _metaArray_io_r_resp_data_3_0_state;
      metaAll_s2_3_1_state <= _metaArray_io_r_resp_data_3_1_state;
      metaAll_s2_4_0_state <= _metaArray_io_r_resp_data_4_0_state;
      metaAll_s2_4_1_state <= _metaArray_io_r_resp_data_4_1_state;
      metaAll_s2_5_0_state <= _metaArray_io_r_resp_data_5_0_state;
      metaAll_s2_5_1_state <= _metaArray_io_r_resp_data_5_1_state;
      metaAll_s2_6_0_state <= _metaArray_io_r_resp_data_6_0_state;
      metaAll_s2_6_1_state <= _metaArray_io_r_resp_data_6_1_state;
      metaAll_s2_7_0_state <= _metaArray_io_r_resp_data_7_0_state;
      metaAll_s2_7_1_state <= _metaArray_io_r_resp_data_7_1_state;
      metaAll_s2_8_0_state <= _metaArray_io_r_resp_data_8_0_state;
      metaAll_s2_8_1_state <= _metaArray_io_r_resp_data_8_1_state;
      metaAll_s2_9_0_state <= _metaArray_io_r_resp_data_9_0_state;
      metaAll_s2_9_1_state <= _metaArray_io_r_resp_data_9_1_state;
      tagAll_s2_0 <= _tagArray_io_r_resp_data_0;
      tagAll_s2_1 <= _tagArray_io_r_resp_data_1;
      tagAll_s2_2 <= _tagArray_io_r_resp_data_2;
      tagAll_s2_3 <= _tagArray_io_r_resp_data_3;
      tagAll_s2_4 <= _tagArray_io_r_resp_data_4;
      tagAll_s2_5 <= _tagArray_io_r_resp_data_5;
      tagAll_s2_6 <= _tagArray_io_r_resp_data_6;
      tagAll_s2_7 <= _tagArray_io_r_resp_data_7;
      tagAll_s2_8 <= _tagArray_io_r_resp_data_8;
      tagAll_s2_9 <= _tagArray_io_r_resp_data_9;
      errorAll_s2_0 <=
        ^_errorAll_s1_T | ~(^_errorAll_s1_T)
        & (|{^({_eccArray_io_r_resp_data_0[4:0], _tagArray_io_r_resp_data_0}
               & 22'h21F800),
             ^({_eccArray_io_r_resp_data_0[3:0], _tagArray_io_r_resp_data_0}
               & 21'h1007F0),
             ^({_eccArray_io_r_resp_data_0[2:0], _tagArray_io_r_resp_data_0} & 20'h9C78E),
             ^({_eccArray_io_r_resp_data_0[1:0], _tagArray_io_r_resp_data_0} & 19'h5366D),
             ^({_eccArray_io_r_resp_data_0[0], _tagArray_io_r_resp_data_0} & 18'h2AD5B)});
      errorAll_s2_1 <=
        ^_errorAll_s1_T_3 | ~(^_errorAll_s1_T_3)
        & (|{^({_eccArray_io_r_resp_data_1[4:0], _tagArray_io_r_resp_data_1}
               & 22'h21F800),
             ^({_eccArray_io_r_resp_data_1[3:0], _tagArray_io_r_resp_data_1}
               & 21'h1007F0),
             ^({_eccArray_io_r_resp_data_1[2:0], _tagArray_io_r_resp_data_1} & 20'h9C78E),
             ^({_eccArray_io_r_resp_data_1[1:0], _tagArray_io_r_resp_data_1} & 19'h5366D),
             ^({_eccArray_io_r_resp_data_1[0], _tagArray_io_r_resp_data_1} & 18'h2AD5B)});
      errorAll_s2_2 <=
        ^_errorAll_s1_T_6 | ~(^_errorAll_s1_T_6)
        & (|{^({_eccArray_io_r_resp_data_2[4:0], _tagArray_io_r_resp_data_2}
               & 22'h21F800),
             ^({_eccArray_io_r_resp_data_2[3:0], _tagArray_io_r_resp_data_2}
               & 21'h1007F0),
             ^({_eccArray_io_r_resp_data_2[2:0], _tagArray_io_r_resp_data_2} & 20'h9C78E),
             ^({_eccArray_io_r_resp_data_2[1:0], _tagArray_io_r_resp_data_2} & 19'h5366D),
             ^({_eccArray_io_r_resp_data_2[0], _tagArray_io_r_resp_data_2} & 18'h2AD5B)});
      errorAll_s2_3 <=
        ^_errorAll_s1_T_9 | ~(^_errorAll_s1_T_9)
        & (|{^({_eccArray_io_r_resp_data_3[4:0], _tagArray_io_r_resp_data_3}
               & 22'h21F800),
             ^({_eccArray_io_r_resp_data_3[3:0], _tagArray_io_r_resp_data_3}
               & 21'h1007F0),
             ^({_eccArray_io_r_resp_data_3[2:0], _tagArray_io_r_resp_data_3} & 20'h9C78E),
             ^({_eccArray_io_r_resp_data_3[1:0], _tagArray_io_r_resp_data_3} & 19'h5366D),
             ^({_eccArray_io_r_resp_data_3[0], _tagArray_io_r_resp_data_3} & 18'h2AD5B)});
      errorAll_s2_4 <=
        ^_errorAll_s1_T_12 | ~(^_errorAll_s1_T_12)
        & (|{^({_eccArray_io_r_resp_data_4[4:0], _tagArray_io_r_resp_data_4}
               & 22'h21F800),
             ^({_eccArray_io_r_resp_data_4[3:0], _tagArray_io_r_resp_data_4}
               & 21'h1007F0),
             ^({_eccArray_io_r_resp_data_4[2:0], _tagArray_io_r_resp_data_4} & 20'h9C78E),
             ^({_eccArray_io_r_resp_data_4[1:0], _tagArray_io_r_resp_data_4} & 19'h5366D),
             ^({_eccArray_io_r_resp_data_4[0], _tagArray_io_r_resp_data_4} & 18'h2AD5B)});
      errorAll_s2_5 <=
        ^_errorAll_s1_T_15 | ~(^_errorAll_s1_T_15)
        & (|{^({_eccArray_io_r_resp_data_5[4:0], _tagArray_io_r_resp_data_5}
               & 22'h21F800),
             ^({_eccArray_io_r_resp_data_5[3:0], _tagArray_io_r_resp_data_5}
               & 21'h1007F0),
             ^({_eccArray_io_r_resp_data_5[2:0], _tagArray_io_r_resp_data_5} & 20'h9C78E),
             ^({_eccArray_io_r_resp_data_5[1:0], _tagArray_io_r_resp_data_5} & 19'h5366D),
             ^({_eccArray_io_r_resp_data_5[0], _tagArray_io_r_resp_data_5} & 18'h2AD5B)});
      errorAll_s2_6 <=
        ^_errorAll_s1_T_18 | ~(^_errorAll_s1_T_18)
        & (|{^({_eccArray_io_r_resp_data_6[4:0], _tagArray_io_r_resp_data_6}
               & 22'h21F800),
             ^({_eccArray_io_r_resp_data_6[3:0], _tagArray_io_r_resp_data_6}
               & 21'h1007F0),
             ^({_eccArray_io_r_resp_data_6[2:0], _tagArray_io_r_resp_data_6} & 20'h9C78E),
             ^({_eccArray_io_r_resp_data_6[1:0], _tagArray_io_r_resp_data_6} & 19'h5366D),
             ^({_eccArray_io_r_resp_data_6[0], _tagArray_io_r_resp_data_6} & 18'h2AD5B)});
      errorAll_s2_7 <=
        ^_errorAll_s1_T_21 | ~(^_errorAll_s1_T_21)
        & (|{^({_eccArray_io_r_resp_data_7[4:0], _tagArray_io_r_resp_data_7}
               & 22'h21F800),
             ^({_eccArray_io_r_resp_data_7[3:0], _tagArray_io_r_resp_data_7}
               & 21'h1007F0),
             ^({_eccArray_io_r_resp_data_7[2:0], _tagArray_io_r_resp_data_7} & 20'h9C78E),
             ^({_eccArray_io_r_resp_data_7[1:0], _tagArray_io_r_resp_data_7} & 19'h5366D),
             ^({_eccArray_io_r_resp_data_7[0], _tagArray_io_r_resp_data_7} & 18'h2AD5B)});
      errorAll_s2_8 <=
        ^_errorAll_s1_T_24 | ~(^_errorAll_s1_T_24)
        & (|{^({_eccArray_io_r_resp_data_8[4:0], _tagArray_io_r_resp_data_8}
               & 22'h21F800),
             ^({_eccArray_io_r_resp_data_8[3:0], _tagArray_io_r_resp_data_8}
               & 21'h1007F0),
             ^({_eccArray_io_r_resp_data_8[2:0], _tagArray_io_r_resp_data_8} & 20'h9C78E),
             ^({_eccArray_io_r_resp_data_8[1:0], _tagArray_io_r_resp_data_8} & 19'h5366D),
             ^({_eccArray_io_r_resp_data_8[0], _tagArray_io_r_resp_data_8} & 18'h2AD5B)});
      errorAll_s2_9 <=
        ^_errorAll_s1_T_27 | ~(^_errorAll_s1_T_27)
        & (|{^({_eccArray_io_r_resp_data_9[4:0], _tagArray_io_r_resp_data_9}
               & 22'h21F800),
             ^({_eccArray_io_r_resp_data_9[3:0], _tagArray_io_r_resp_data_9}
               & 21'h1007F0),
             ^({_eccArray_io_r_resp_data_9[2:0], _tagArray_io_r_resp_data_9} & 20'h9C78E),
             ^({_eccArray_io_r_resp_data_9[1:0], _tagArray_io_r_resp_data_9} & 19'h5366D),
             ^({_eccArray_io_r_resp_data_9[0], _tagArray_io_r_resp_data_9} & 18'h2AD5B)});
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:8];
    initial begin
      `ifdef INIT_RANDOM_PROLOG_
        `INIT_RANDOM_PROLOG_
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT
        for (logic [3:0] i = 4'h0; i < 4'h9; i += 4'h1) begin
          _RANDOM[i] = `RANDOM;
        end
        resetFinish = _RANDOM[4'h0][0];
        resetIdx = _RANDOM[4'h0][11:1];
        clk_en = _RANDOM[4'h0][12];
        reqReg_tag = _RANDOM[4'h0][30:14];
        reqValidReg = _RANDOM[4'h1][25];
        reqValidReg_REG = _RANDOM[4'h1][26];
        hit_s2 = _RANDOM[4'h1][27];
        way_s2 = _RANDOM[4'h1][31:28];
        metaAll_s2_0_0_state = _RANDOM[4'h2][1:0];
        metaAll_s2_0_1_state = _RANDOM[4'h2][3:2];
        metaAll_s2_1_0_state = _RANDOM[4'h2][5:4];
        metaAll_s2_1_1_state = _RANDOM[4'h2][7:6];
        metaAll_s2_2_0_state = _RANDOM[4'h2][9:8];
        metaAll_s2_2_1_state = _RANDOM[4'h2][11:10];
        metaAll_s2_3_0_state = _RANDOM[4'h2][13:12];
        metaAll_s2_3_1_state = _RANDOM[4'h2][15:14];
        metaAll_s2_4_0_state = _RANDOM[4'h2][17:16];
        metaAll_s2_4_1_state = _RANDOM[4'h2][19:18];
        metaAll_s2_5_0_state = _RANDOM[4'h2][21:20];
        metaAll_s2_5_1_state = _RANDOM[4'h2][23:22];
        metaAll_s2_6_0_state = _RANDOM[4'h2][25:24];
        metaAll_s2_6_1_state = _RANDOM[4'h2][27:26];
        metaAll_s2_7_0_state = _RANDOM[4'h2][29:28];
        metaAll_s2_7_1_state = _RANDOM[4'h2][31:30];
        metaAll_s2_8_0_state = _RANDOM[4'h3][1:0];
        metaAll_s2_8_1_state = _RANDOM[4'h3][3:2];
        metaAll_s2_9_0_state = _RANDOM[4'h3][5:4];
        metaAll_s2_9_1_state = _RANDOM[4'h3][7:6];
        tagAll_s2_0 = _RANDOM[4'h3][24:8];
        tagAll_s2_1 = {_RANDOM[4'h3][31:25], _RANDOM[4'h4][9:0]};
        tagAll_s2_2 = _RANDOM[4'h4][26:10];
        tagAll_s2_3 = {_RANDOM[4'h4][31:27], _RANDOM[4'h5][11:0]};
        tagAll_s2_4 = _RANDOM[4'h5][28:12];
        tagAll_s2_5 = {_RANDOM[4'h5][31:29], _RANDOM[4'h6][13:0]};
        tagAll_s2_6 = _RANDOM[4'h6][30:14];
        tagAll_s2_7 = {_RANDOM[4'h6][31], _RANDOM[4'h7][15:0]};
        tagAll_s2_8 = {_RANDOM[4'h7][31:16], _RANDOM[4'h8][0]};
        tagAll_s2_9 = _RANDOM[4'h8][17:1];
        errorAll_s2_0 = _RANDOM[4'h8][18];
        errorAll_s2_1 = _RANDOM[4'h8][19];
        errorAll_s2_2 = _RANDOM[4'h8][20];
        errorAll_s2_3 = _RANDOM[4'h8][21];
        errorAll_s2_4 = _RANDOM[4'h8][22];
        errorAll_s2_5 = _RANDOM[4'h8][23];
        errorAll_s2_6 = _RANDOM[4'h8][24];
        errorAll_s2_7 = _RANDOM[4'h8][25];
        errorAll_s2_8 = _RANDOM[4'h8][26];
        errorAll_s2_9 = _RANDOM[4'h8][27];
        resetMask = _RANDOM[4'h8][28];
      `endif // RANDOMIZE_REG_INIT
      if (reset) begin
        resetFinish = 1'h0;
        resetIdx = 11'h7FF;
        clk_en = 1'h0;
        reqValidReg = 1'h0;
        hit_s2 = 1'h0;
        way_s2 = 4'h0;
        resetMask = 1'h0;
      end
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  ClkDiv2SRAMTemplate_40 metaArray (
    .clock                        (_ClockGate_Q),
    .io_r_req_valid               (_metas_T),
    .io_r_req_bits_setIdx         (io_read_bits_set),
    .io_r_resp_data_0_0_state     (_metaArray_io_r_resp_data_0_0_state),
    .io_r_resp_data_0_1_state     (_metaArray_io_r_resp_data_0_1_state),
    .io_r_resp_data_1_0_state     (_metaArray_io_r_resp_data_1_0_state),
    .io_r_resp_data_1_1_state     (_metaArray_io_r_resp_data_1_1_state),
    .io_r_resp_data_2_0_state     (_metaArray_io_r_resp_data_2_0_state),
    .io_r_resp_data_2_1_state     (_metaArray_io_r_resp_data_2_1_state),
    .io_r_resp_data_3_0_state     (_metaArray_io_r_resp_data_3_0_state),
    .io_r_resp_data_3_1_state     (_metaArray_io_r_resp_data_3_1_state),
    .io_r_resp_data_4_0_state     (_metaArray_io_r_resp_data_4_0_state),
    .io_r_resp_data_4_1_state     (_metaArray_io_r_resp_data_4_1_state),
    .io_r_resp_data_5_0_state     (_metaArray_io_r_resp_data_5_0_state),
    .io_r_resp_data_5_1_state     (_metaArray_io_r_resp_data_5_1_state),
    .io_r_resp_data_6_0_state     (_metaArray_io_r_resp_data_6_0_state),
    .io_r_resp_data_6_1_state     (_metaArray_io_r_resp_data_6_1_state),
    .io_r_resp_data_7_0_state     (_metaArray_io_r_resp_data_7_0_state),
    .io_r_resp_data_7_1_state     (_metaArray_io_r_resp_data_7_1_state),
    .io_r_resp_data_8_0_state     (_metaArray_io_r_resp_data_8_0_state),
    .io_r_resp_data_8_1_state     (_metaArray_io_r_resp_data_8_1_state),
    .io_r_resp_data_9_0_state     (_metaArray_io_r_resp_data_9_0_state),
    .io_r_resp_data_9_1_state     (_metaArray_io_r_resp_data_9_1_state),
    .io_w_req_valid               (~resetFinish | io_dir_w_valid),
    .io_w_req_bits_setIdx         (resetFinish ? io_dir_w_bits_set : resetIdx),
    .io_w_req_bits_data_0_0_state (_GEN_5),
    .io_w_req_bits_data_0_1_state (_GEN_6),
    .io_w_req_bits_data_1_0_state (_GEN_5),
    .io_w_req_bits_data_1_1_state (_GEN_6),
    .io_w_req_bits_data_2_0_state (_GEN_5),
    .io_w_req_bits_data_2_1_state (_GEN_6),
    .io_w_req_bits_data_3_0_state (_GEN_5),
    .io_w_req_bits_data_3_1_state (_GEN_6),
    .io_w_req_bits_data_4_0_state (_GEN_5),
    .io_w_req_bits_data_4_1_state (_GEN_6),
    .io_w_req_bits_data_5_0_state (_GEN_5),
    .io_w_req_bits_data_5_1_state (_GEN_6),
    .io_w_req_bits_data_6_0_state (_GEN_5),
    .io_w_req_bits_data_6_1_state (_GEN_6),
    .io_w_req_bits_data_7_0_state (_GEN_5),
    .io_w_req_bits_data_7_1_state (_GEN_6),
    .io_w_req_bits_data_8_0_state (_GEN_5),
    .io_w_req_bits_data_8_1_state (_GEN_6),
    .io_w_req_bits_data_9_0_state (_GEN_5),
    .io_w_req_bits_data_9_1_state (_GEN_6),
    .io_w_req_bits_waymask        (resetFinish ? _GEN_7[9:0] : 10'h3FF)
  );
  ClockGate ClockGate (
    .TE (1'h0),
    .E  (clk_en),
    .CK (clock),
    .Q  (_ClockGate_Q)
  );
  ClkDiv2SRAMTemplate_41 tagArray (
    .clock                 (_ClockGate_Q),
    .io_r_req_valid        (_metas_T),
    .io_r_req_bits_setIdx  (io_read_bits_set),
    .io_r_resp_data_0      (_tagArray_io_r_resp_data_0),
    .io_r_resp_data_1      (_tagArray_io_r_resp_data_1),
    .io_r_resp_data_2      (_tagArray_io_r_resp_data_2),
    .io_r_resp_data_3      (_tagArray_io_r_resp_data_3),
    .io_r_resp_data_4      (_tagArray_io_r_resp_data_4),
    .io_r_resp_data_5      (_tagArray_io_r_resp_data_5),
    .io_r_resp_data_6      (_tagArray_io_r_resp_data_6),
    .io_r_resp_data_7      (_tagArray_io_r_resp_data_7),
    .io_r_resp_data_8      (_tagArray_io_r_resp_data_8),
    .io_r_resp_data_9      (_tagArray_io_r_resp_data_9),
    .io_w_req_valid        (io_tag_w_valid),
    .io_w_req_bits_setIdx  (io_tag_w_bits_set),
    .io_w_req_bits_data_0  (io_tag_w_bits_tag),
    .io_w_req_bits_data_1  (io_tag_w_bits_tag),
    .io_w_req_bits_data_2  (io_tag_w_bits_tag),
    .io_w_req_bits_data_3  (io_tag_w_bits_tag),
    .io_w_req_bits_data_4  (io_tag_w_bits_tag),
    .io_w_req_bits_data_5  (io_tag_w_bits_tag),
    .io_w_req_bits_data_6  (io_tag_w_bits_tag),
    .io_w_req_bits_data_7  (io_tag_w_bits_tag),
    .io_w_req_bits_data_8  (io_tag_w_bits_tag),
    .io_w_req_bits_data_9  (io_tag_w_bits_tag),
    .io_w_req_bits_waymask (_GEN_0[9:0])
  );
  ClkDiv2SRAMTemplate_42 eccArray (
    .clock                 (_ClockGate_Q),
    .io_r_req_valid        (_metas_T),
    .io_r_req_bits_setIdx  (io_read_bits_set),
    .io_r_resp_data_0      (_eccArray_io_r_resp_data_0),
    .io_r_resp_data_1      (_eccArray_io_r_resp_data_1),
    .io_r_resp_data_2      (_eccArray_io_r_resp_data_2),
    .io_r_resp_data_3      (_eccArray_io_r_resp_data_3),
    .io_r_resp_data_4      (_eccArray_io_r_resp_data_4),
    .io_r_resp_data_5      (_eccArray_io_r_resp_data_5),
    .io_r_resp_data_6      (_eccArray_io_r_resp_data_6),
    .io_r_resp_data_7      (_eccArray_io_r_resp_data_7),
    .io_r_resp_data_8      (_eccArray_io_r_resp_data_8),
    .io_r_resp_data_9      (_eccArray_io_r_resp_data_9),
    .io_w_req_valid        (io_tag_w_valid),
    .io_w_req_bits_setIdx  (io_tag_w_bits_set),
    .io_w_req_bits_data_0  (_GEN),
    .io_w_req_bits_data_1  (_GEN),
    .io_w_req_bits_data_2  (_GEN),
    .io_w_req_bits_data_3  (_GEN),
    .io_w_req_bits_data_4  (_GEN),
    .io_w_req_bits_data_5  (_GEN),
    .io_w_req_bits_data_6  (_GEN),
    .io_w_req_bits_data_7  (_GEN),
    .io_w_req_bits_data_8  (_GEN),
    .io_w_req_bits_data_9  (_GEN),
    .io_w_req_bits_waymask (_GEN_0[9:0])
  );
  MaxPeriodFibonacciLFSR_3 lfsr_prng (
    .clock        (clock),
    .reset        (reset),
    .io_increment (io_tag_w_valid),
    .io_out_0     (_lfsr_prng_io_out_0),
    .io_out_1     (_lfsr_prng_io_out_1),
    .io_out_2     (_lfsr_prng_io_out_2),
    .io_out_3     (_lfsr_prng_io_out_3),
    .io_out_4     (_lfsr_prng_io_out_4),
    .io_out_5     (_lfsr_prng_io_out_5),
    .io_out_6     (_lfsr_prng_io_out_6),
    .io_out_7     (/* unused */),
    .io_out_8     (/* unused */),
    .io_out_9     (/* unused */),
    .io_out_10    (/* unused */),
    .io_out_11    (/* unused */),
    .io_out_12    (/* unused */),
    .io_out_13    (/* unused */),
    .io_out_14    (/* unused */),
    .io_out_15    (/* unused */)
  );
  assign io_read_ready = io_read_ready_0;
  assign io_resp_bits_hit = hit_s2;
  assign io_resp_bits_way = way_s2;
  assign io_resp_bits_tag = _GEN_3[way_s2];
  assign io_resp_bits_dir_0_state = _GEN_1[way_s2];
  assign io_resp_bits_dir_1_state = _GEN_2[way_s2];
  assign io_resp_bits_error = hit_s2 & _GEN_4[way_s2];
endmodule

